/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: Unknown
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void NOP_1FFFEC8C();
void kong_1FFFEC94();
void meiyong_1FFFECAA();
void guanzhongduan_1FFFECBE();
void kaizhongduan_1FFFECC2();
signed int systick_1FFFECC8();
signed int fuwei_1FFFECD8();
signed int kanmengou_1FFFECF4();
signed __int64 sub_1FFFEE64();
signed int RCCshizhong_1FFFEE84();
signed int qingchuRCC_1FFFEEA8();
signed int sub_1FFFEECC();
signed int __fastcall sub_1FFFEF10(int a1);
_DWORD *sub_1FFFEF50();
signed int FPECjiesuo_1FFFEF62();
signed int OPTWREjiesuo_1FFFEF6E();
signed int flashmang_1FFFEF7A();
int __fastcall xieflash_1FFFEF9A(int a1, int a2);
int __fastcall yecachu_1FFFEFDA(int a1);
unsigned int zhengpian_1FFFEFF8();
unsigned int xuanzezijiecachu_1FFFF020();
signed int __fastcall zijiebiancheng_1FFFF048(int a1);
signed int __fastcall xiebaohu_1FFFF0A6(int a1);
signed int jiancedubaohu_1FFFF124();
signed int xuanzezijieqiangzhigengxin_1FFFF132();
int __fastcall sub_1FFFF164(__int16 a1);
int sub_1FFFF172();
int weigou_1FFFF19A();
signed int __fastcall sub_1FFFF1B2(int a1, _BYTE *a2);
signed int __fastcall sub_1FFFF1E0(unsigned int a1, _WORD *a2);
signed int sub_1FFFF22E();
int __fastcall sub_1FFFF596(unsigned int a1, unsigned int a2);
signed int sub_1FFFF740();
void BKPTduandian_1FFFF748();

//-------------------------------------------------------------------------
// Data declarations

int dword_1FFFEC00 = 536872560; // weak
__int16 word_1FFFF800 = 21930; // weak
__int16 word_1FFFF802 = 65535; // weak
__int16 word_1FFFF804 = 65535; // weak
__int16 word_1FFFF806 = 65535; // weak
__int16 word_1FFFF808 = 65535; // weak
__int16 word_1FFFF80A = 65535; // weak


//----- (1FFFEC8C) --------------------------------------------------------
void NOP_1FFFEC8C()
{
  ;
}

//----- (1FFFEC94) --------------------------------------------------------
void kong_1FFFEC94()
{
  ;
}

//----- (1FFFECAA) --------------------------------------------------------
void meiyong_1FFFECAA()
{
  kong_1FFFEC94();
  BKPTduandian_1FFFF748();
}

//----- (1FFFECBE) --------------------------------------------------------
void guanzhongduan_1FFFECBE()
{
  __disable_irq();
}

//----- (1FFFECC2) --------------------------------------------------------
void kaizhongduan_1FFFECC2()
{
  __enable_irq();
}

//----- (1FFFECC8) --------------------------------------------------------
signed int systick_1FFFECC8()
{
  signed int result; // r0@1

  result = -536813568;
  vE000E010 = 0;
  vE000E018 = 0;
  vE000E014 = 0x80000;
  return result;
}

//----- (1FFFECD8) --------------------------------------------------------
signed int fuwei_1FFFECD8()
{
  signed int result; // r0@1

  result = 100270084;
  vE000ED0C = 100270084;
  return result;
}

//----- (1FFFECF4) --------------------------------------------------------
signed int kanmengou_1FFFECF4()
{
  signed int v0; // r0@13
  signed int v1; // r0@19
  signed int v2; // r0@23

  v40003004 = 6;
  v40003000 = 43690;
  sub_1FFFEECC();
  vE000ED08 = &dword_1FFFEC00;
  if ( jiancedubaohu_1FFFF124() == 1 )
  {
    for ( v20000004 = 536875004; v20000004 >= 0x20000800u; v20000004 -= 4 )
      *v20000004 = 0;
    v20000004 = 0;
  }
  systick_1FFFECC8();
  vE000E010 = 4;
  vE000E014 = 0x80000;
  v40021018 = 0x4000;
  v40021014 = 131092;
  FPECjiesuo_1FFFEF62();
  v48000000 = 671612928;
  v48000004 = 0;
  v48000008 = -63176704;
  v4800000C = 1410596864;
  v48000024 = 0;
  while ( 1 )
  {
    if ( !(v48000010 & 0x400) )
      v20000008 = 1;
    if ( !((unsigned int)v48000010 >> 15) )
      v2000000C = 1;
    if ( v20000008 == 1 && v48000010 & 0x400 )
      break;
LABEL_21:
    if ( v2000000C == 1 && (unsigned int)v48000010 >> 15 )
    {
      vE000E010 = 5;
      v2 = 24575;
      while ( (unsigned int)v48000010 >> 15 )
      {
        if ( !v2 )
          goto LABEL_31;
        --v2;
      }
      if ( v2 )
      {
        v20000004 = 0x80000 - vE000E018;
        v48000000 = -1476395008;
        v1 = 285212672;
        goto LABEL_30;
      }
LABEL_31:
      v2000000C = 0;
      systick_1FFFECC8();
    }
  }
  vE000E010 = 5;
  v0 = 24575;
  while ( v48000010 & 0x400 )
  {
    if ( !v0 )
    {
LABEL_20:
      v20000008 = 0;
      systick_1FFFECC8();
      goto LABEL_21;
    }
    --v0;
  }
  if ( !v0 )
    goto LABEL_20;
  v20000004 = 0x80000 - vE000E018;
  v48000000 = 673710080;
  v1 = 272;
LABEL_30:
  v48000024 = v1;
  systick_1FFFECC8();
  return 1;
}
// 1FFFEC00: using guessed type int dword_1FFFEC00;

//----- (1FFFEE64) --------------------------------------------------------
signed __int64 sub_1FFFEE64()
{
  return 2305850087856668784i64;
}

//----- (1FFFEE84) --------------------------------------------------------
signed int RCCshizhong_1FFFEE84()
{
  signed int result; // r0@1

  result = 1073876992;
  v40021000 |= 1u;
  v40021004 = 0;
  v40021007 = 0;
  v40021002 = 0;
  v40021006 = 0;
  v4002102C = 0;
  v40021030 = 0;
  v40021034 = -128;
  v40021008 = 0;
  return result;
}

//----- (1FFFEEA8) --------------------------------------------------------
signed int qingchuRCC_1FFFEEA8()
{
  signed int result; // r0@1

  RCCshizhong_1FFFEE84();
  result = 1073876992;
  v4002100C = 0;
  v40021010 = 0;
  v40021028 = 0;
  v40021018 = 0;
  v4002101C = 0;
  v40021014 = 20;
  return result;
}

//----- (1FFFEECC) --------------------------------------------------------
signed int sub_1FFFEECC()
{
  signed int v0; // r4@1
  signed int result; // r0@8

  v0 = 0x1FFFF;
  RCCshizhong_1FFFEE84();
  v40022000 = 0;
  v40021006 = 16;
  v40021003 = 1;
  while ( v40021003 != 3 )
  {
    if ( !v0 )
      goto LABEL_7;
    --v0;
  }
  if ( v0 )
    goto LABEL_8;
LABEL_7:
  fuwei_1FFFECD8();
LABEL_8:
  result = 2;
  v40021004 = 2;
  return result;
}

//----- (1FFFEF10) --------------------------------------------------------
signed int __fastcall sub_1FFFEF10(int a1)
{
  signed int result; // r0@2

  if ( (unsigned int)(a1 - 0x8000000) >= 0x8000 )
  {
    if ( (unsigned int)(a1 - 536872960) >= 0x800 )
    {
      if ( (unsigned int)(a1 - 536868864) >= 0xF )
      {
        if ( (unsigned int)(a1 - 536865792) >= 0xBFF )
          result = 1;
        else
          result = 5;
      }
      else
      {
        result = 4;
      }
    }
    else
    {
      result = 3;
    }
  }
  else
  {
    result = 2;
  }
  return result;
}

//----- (1FFFEF50) --------------------------------------------------------
_DWORD *sub_1FFFEF50()
{
  _DWORD *result; // r0@1

  result = (_DWORD *)536875004;
  do
  {
    *result = 0;
    --result;
  }
  while ( result != (_DWORD *)0x20000000 );
  return result;
}

//----- (1FFFEF62) --------------------------------------------------------
// FPEC解锁
signed int FPECjiesuo_1FFFEF62()
{
  signed int result; // r0@1

  result = 1073881088;
  v40022004 = -839939669;
  return result;
}

//----- (1FFFEF6E) --------------------------------------------------------
// OPTWRE解锁
signed int OPTWREjiesuo_1FFFEF6E()
{
  signed int result; // r0@1

  result = 1073881088;
  v40022008 = -839939669;
  return result;
}

//----- (1FFFEF7A) --------------------------------------------------------
// flash 忙
signed int flashmang_1FFFEF7A()
{
  signed int result; // r0@1

  result = 4095;
  while ( v4002200C << 31 )
  {
    if ( !result )
      return fuwei_1FFFECD8();
    --result;
  }
  if ( result )
    return result;
  return fuwei_1FFFECD8();
}

//----- (1FFFEF9A) --------------------------------------------------------
// 编程
int __fastcall xieflash_1FFFEF9A(int a1, int a2)
{
  int v2; // r6@1
  int v3; // r5@1
  int result; // r0@5

  v2 = a1;
  v3 = a2;
  flashmang_1FFFEF7A();
  v40022010 |= 1u;
  *(_WORD *)v2 = v3;
  flashmang_1FFFEF7A();
  if ( !(v4002200C & 4) )
  {
    *(_WORD *)(v2 + 2) = HIWORD(v3);
    flashmang_1FFFEF7A();
  }
  if ( v4002200C & 4 )
    v4002200C |= 4u;
  result = 2 * (v40022010 >> 1);
  v40022010 = 2 * (v40022010 >> 1);
  return result;
}

//----- (1FFFEFDA) --------------------------------------------------------
// 页擦除
int __fastcall yecachu_1FFFEFDA(int a1)
{
  int v1; // r5@1
  int result; // r0@1

  v1 = a1;
  flashmang_1FFFEF7A();
  v40022014 = v1;
  v40022010 = 66;
  flashmang_1FFFEF7A();
  result = 0;
  v40022010 = 0;
  return result;
}

//----- (1FFFEFF8) --------------------------------------------------------
// 整片擦除
unsigned int zhengpian_1FFFEFF8()
{
  unsigned int result; // r0@1

  OPTWREjiesuo_1FFFEF6E();
  flashmang_1FFFEF7A();
  v40022010 |= 4u;
  v40022010 |= 0x40u;
  flashmang_1FFFEF7A();
  result = v40022010 & 0xFFFFFFFB;
  v40022010 &= 0xFFFFFFFB;
  return result;
}

//----- (1FFFF020) --------------------------------------------------------
// 选项字节擦除
unsigned int xuanzezijiecachu_1FFFF020()
{
  unsigned int result; // r0@1

  OPTWREjiesuo_1FFFEF6E();
  flashmang_1FFFEF7A();
  v40022010 |= 0x20u;
  v40022010 |= 0x40u;
  flashmang_1FFFEF7A();
  result = v40022010 & 0xFFFFFFDF;
  v40022010 &= 0xFFFFFFDF;
  return result;
}

//----- (1FFFF048) --------------------------------------------------------
// 字节编程
// write access to const memory has been detected, the output may be wrong!
signed int __fastcall zijiebiancheng_1FFFF048(int a1)
{
  int v1; // r0@1
  int v2; // r5@1
  unsigned int v3; // r6@1
  signed int result; // r0@5

  v1 = ~a1;
  v2 = (unsigned __int8)v1;
  v3 = (unsigned int)(v1 << 16) >> 24;
  xuanzezijiecachu_1FFFF020();
  FPECjiesuo_1FFFEF62();
  OPTWREjiesuo_1FFFEF6E();
  v40022010 |= 0x10u;
  word_1FFFF800 = 170;
  flashmang_1FFFEF7A();
  word_1FFFF802 = 255;
  flashmang_1FFFEF7A();
  if ( v2 != 255 )
  {
    word_1FFFF808 = v2;
    flashmang_1FFFEF7A();
  }
  if ( v3 != 255 )
  {
    word_1FFFF80A = v3;
    flashmang_1FFFEF7A();
  }
  result = 1073881088;
  v40022010 &= 0xFFFFFFEF;
  return result;
}
// 1FFFF092: write access to const memory at 1FFFF80A has been detected
// 1FFFF088: write access to const memory at 1FFFF808 has been detected
// 1FFFF07E: write access to const memory at 1FFFF802 has been detected
// 1FFFF074: write access to const memory at 1FFFF800 has been detected
// 1FFFF800: using guessed type __int16 word_1FFFF800;
// 1FFFF802: using guessed type __int16 word_1FFFF802;
// 1FFFF808: using guessed type __int16 word_1FFFF808;
// 1FFFF80A: using guessed type __int16 word_1FFFF80A;

//----- (1FFFF0A6) --------------------------------------------------------
// 写保护
// write access to const memory has been detected, the output may be wrong!
signed int __fastcall xiebaohu_1FFFF0A6(int a1)
{
  int v1; // ST08_4@1
  signed __int16 v2; // r0@2
  signed int result; // r0@4

  v1 = a1;
  flashmang_1FFFEF7A();
  xuanzezijiecachu_1FFFF020();
  FPECjiesuo_1FFFEF62();
  OPTWREjiesuo_1FFFEF6E();
  flashmang_1FFFEF7A();
  v40022010 |= 0x10u;
  if ( v1 )
  {
    word_1FFFF802 = 255;
    flashmang_1FFFEF7A();
    word_1FFFF804 = 255;
    flashmang_1FFFEF7A();
    word_1FFFF806 = 255;
    flashmang_1FFFEF7A();
    word_1FFFF808 = 255;
    flashmang_1FFFEF7A();
    word_1FFFF808 = 255;
    flashmang_1FFFEF7A();
    v2 = 0;
  }
  else
  {
    v2 = 170;
  }
  word_1FFFF800 = v2;
  flashmang_1FFFEF7A();
  result = 1073881088;
  v40022010 &= 0xFFFFFFEF;
  return result;
}
// 1FFFF112: write access to const memory at 1FFFF800 has been detected
// 1FFFF106: write access to const memory at 1FFFF808 has been detected
// 1FFFF0FC: write access to const memory at 1FFFF808 has been detected
// 1FFFF0F2: write access to const memory at 1FFFF806 has been detected
// 1FFFF0EA: write access to const memory at 1FFFF804 has been detected
// 1FFFF0E2: write access to const memory at 1FFFF802 has been detected
// 1FFFF800: using guessed type __int16 word_1FFFF800;
// 1FFFF802: using guessed type __int16 word_1FFFF802;
// 1FFFF804: using guessed type __int16 word_1FFFF804;
// 1FFFF806: using guessed type __int16 word_1FFFF806;
// 1FFFF808: using guessed type __int16 word_1FFFF808;
// 1FFFF80A: using guessed type __int16 word_1FFFF80A;

//----- (1FFFF124) --------------------------------------------------------
// 检测读保护
signed int jiancedubaohu_1FFFF124()
{
  signed int result; // r0@1

  result = 0;
  if ( v4002201C & 2 )
    result = 1;
  return result;
}

//----- (1FFFF132) --------------------------------------------------------
// 选项字节强制更新
signed int xuanzezijieqiangzhigengxin_1FFFF132()
{
  signed int result; // r0@1

  result = 1073881088;
  v40022010 |= 0x2000u;
  return result;
}

//----- (1FFFF164) --------------------------------------------------------
int __fastcall sub_1FFFF164(__int16 a1)
{
  int v1; // r1@1
  int result; // r0@2

  v1 = v20000000;
  *(_WORD *)(v20000000 + 40) = a1;
  do
    result = *(_DWORD *)(v1 + 28) << 25;
  while ( !(*(_DWORD *)(v1 + 28) & 0x40) );
  return result;
}

//----- (1FFFF172) --------------------------------------------------------
int sub_1FFFF172()
{
  __int16 v0; // r0@1
  _DWORD *v1; // r1@1
  int v2; // r2@1
  int result; // r0@1

  guanzhongduan_1FFFECBE();
  v0 = sub_1FFFF596(v20000004, 7u);
  v1 = (_DWORD *)v20000000;
  *(_WORD *)(v20000000 + 12) = v0;
  *v1 = 5133;
  sub_1FFFF164(121);
  result = *(_WORD *)(*(_DWORD *)v2 + 36);
  v20000004 = *(_WORD *)(*(_DWORD *)v2 + 36);
  return result;
}

//----- (1FFFF19A) --------------------------------------------------------
int weigou_1FFFF19A()
{
  while ( !(*(_DWORD *)(v20000000 + 28) & 0x20) )
    v40003000 = 43690;
  return (unsigned __int8)*(_WORD *)(v20000000 + 36);
}

//----- (1FFFF1B2) --------------------------------------------------------
signed int __fastcall sub_1FFFF1B2(int a1, _BYTE *a2)
{
  _BYTE *v2; // r6@1
  int v3; // r5@1
  int v4; // r4@1
  int v5; // r0@2
  signed int result; // r0@4

  v2 = a2;
  v3 = a1 + 1;
  v4 = a1;
  if ( a1 != -1 )
  {
    do
    {
      v5 = weigou_1FFFF19A();
      v4 ^= v5;
      *v2++ = v5;
      --v3;
    }
    while ( v3 );
  }
  if ( weigou_1FFFF19A() == v4 )
  {
    result = 170;
  }
  else
  {
    sub_1FFFF164(31);
    result = 85;
  }
  return result;
}

//----- (1FFFF1E0) --------------------------------------------------------
signed int __fastcall sub_1FFFF1E0(unsigned int a1, _WORD *a2)
{
  _WORD *v2; // r6@1
  int v3; // r5@1
  int v4; // r7@1
  int v5; // r4@1
  __int16 v6; // r7@2
  __int16 v7; // r0@2
  int v8; // r12@2
  signed int result; // r0@6

  v2 = a2;
  v3 = a1 + 1;
  v4 = (unsigned __int8)a1 ^ (a1 >> 8);
  v5 = a1 + 1;
  if ( a1 != -1 )
  {
    do
    {
      v6 = (unsigned __int16)weigou_1FFFF19A() << 8;
      v7 = weigou_1FFFF19A() | v6;
      v4 = v8 ^ (unsigned __int8)v7;
      if ( (unsigned int)(v3 - v5) < 0x400 )
      {
        *v2 = v7;
        ++v2;
      }
      --v5;
    }
    while ( v5 );
  }
  if ( weigou_1FFFF19A() == v4 )
  {
    result = 170;
  }
  else
  {
    sub_1FFFF164(31);
    result = 85;
  }
  return result;
}

//----- (1FFFF22E) --------------------------------------------------------
signed int sub_1FFFF22E()
{
  int v0; // r4@2
  int v1; // r0@2
  int v2; // r6@2
  int v3; // r5@2
  int v4; // r0@2
  int v5; // r4@2
  int v6; // r5@2
  int v7; // r0@2
  int v8; // r4@2
  signed int result; // r0@3

  if ( jiancedubaohu_1FFFF124()
    || (sub_1FFFF164(121),
        v0 = weigou_1FFFF19A(),
        v1 = weigou_1FFFF19A(),
        v2 = (v1 << 16) | (v0 << 24),
        v3 = v0 ^ v1,
        v4 = weigou_1FFFF19A(),
        v5 = (v4 << 8) | v2,
        v6 = v3 ^ v4,
        v7 = weigou_1FFFF19A(),
        v8 = v5 | v7,
        weigou_1FFFF19A() != (v6 ^ v7)) )
  {
    sub_1FFFF164(31);
    result = 1431655765;
  }
  else
  {
    sub_1FFFF164(121);
    result = v8;
  }
  return result;
}

//----- (1FFFF596) --------------------------------------------------------
int __fastcall sub_1FFFF596(unsigned int a1, unsigned int a2)
{
  int v2; // r2@1
  unsigned __int8 v3; // cf@3
  int v4; // r2@5
  unsigned __int8 v5; // cf@5
  int v6; // r2@7
  unsigned __int8 v7; // cf@7
  int v8; // r2@9
  unsigned __int8 v9; // cf@9
  unsigned __int8 v10; // cf@12
  int v11; // r2@14
  unsigned __int8 v12; // cf@14
  int v13; // r2@16
  unsigned __int8 v14; // cf@16
  unsigned int v16; // r1@19
  signed int v17; // r2@19
  unsigned int v18; // r3@19
  unsigned __int8 v19; // cf@25
  int v20; // r2@27
  unsigned __int8 v21; // cf@27
  int v22; // r2@29
  unsigned __int8 v23; // cf@29
  int v24; // r2@31
  unsigned __int8 v25; // cf@31
  int v26; // r2@33
  unsigned __int8 v27; // cf@33
  int v28; // r2@35
  unsigned __int8 v29; // cf@35
  int v30; // off@37
  unsigned __int8 v31; // cf@38

  v2 = 0;
  if ( a1 >> 4 < a2 )
  {
LABEL_12:
    v10 = a1 >> 3 >= a2;
    if ( a1 >> 3 >= a2 )
    {
      v10 = a1 >= 8 * a2;
      a1 -= 8 * a2;
    }
    v11 = v2 + v10 + v2;
    v12 = a1 >> 2 >= a2;
    if ( a1 >> 2 >= a2 )
    {
      v12 = a1 >= 4 * a2;
      a1 -= 4 * a2;
    }
    v13 = v11 + v12 + v11;
    v14 = a1 >> 1 >= a2;
    if ( a1 >> 1 >= a2 )
    {
      v14 = a1 >= 2 * a2;
      a1 -= 2 * a2;
    }
    return v13 + v14 + v13 + (a1 >= a2) + v13 + v14 + v13;
  }
  if ( a1 >> 8 < a2 )
  {
    v3 = a1 >> 7 >= a2;
    if ( a1 >> 7 >= a2 )
    {
      v3 = a1 >= a2 << 7;
      a1 -= a2 << 7;
    }
    v4 = v3;
    v5 = a1 >> 6 >= a2;
    if ( a1 >> 6 >= a2 )
    {
      v5 = a1 >= a2 << 6;
      a1 -= a2 << 6;
    }
    v6 = v4 + v5 + v4;
    v7 = a1 >> 5 >= a2;
    if ( a1 >> 5 >= a2 )
    {
      v7 = a1 >= 32 * a2;
      a1 -= 32 * a2;
    }
    v8 = v6 + v7 + v6;
    v9 = a1 >> 4 >= a2;
    if ( a1 >> 4 >= a2 )
    {
      v9 = a1 >= 16 * a2;
      a1 -= 16 * a2;
    }
    v2 = v8 + v9 + v8;
    goto LABEL_12;
  }
  v16 = a2 << 6;
  v17 = __rev(0xFCu);
  v18 = a1 >> 8;
  if ( a1 >> 8 >= v16 )
  {
    v16 <<= 6;
    v17 >>= 6;
    if ( v18 >= v16 )
    {
      v16 <<= 6;
      v17 >>= 6;
      if ( v18 >= v16 )
      {
        v16 <<= 6;
        if ( !v16 )
          return 0;
        v17 >>= 6;
      }
    }
  }
  while ( 1 )
  {
    v19 = a1 >> 7 >= v16;
    if ( a1 >> 7 >= v16 )
    {
      v19 = a1 >= v16 << 7;
      a1 -= v16 << 7;
    }
    v20 = v17 + v19 + v17;
    v21 = a1 >> 6 >= v16;
    if ( a1 >> 6 >= v16 )
    {
      v21 = a1 >= v16 << 6;
      a1 -= v16 << 6;
    }
    v22 = v20 + v21 + v20;
    v23 = a1 >> 5 >= v16;
    if ( a1 >> 5 >= v16 )
    {
      v23 = a1 >= 32 * v16;
      a1 -= 32 * v16;
    }
    v24 = v22 + v23 + v22;
    v25 = a1 >> 4 >= v16;
    if ( a1 >> 4 >= v16 )
    {
      v25 = a1 >= 16 * v16;
      a1 -= 16 * v16;
    }
    v26 = v24 + v25 + v24;
    v27 = a1 >> 3 >= v16;
    if ( a1 >> 3 >= v16 )
    {
      v27 = a1 >= 8 * v16;
      a1 -= 8 * v16;
    }
    v28 = v26 + v27 + v26;
    v29 = a1 >> 2 >= v16;
    if ( a1 >> 2 >= v16 )
    {
      v29 = a1 >= 4 * v16;
      a1 -= 4 * v16;
    }
    v30 = v29 + v28;
    v3 = __CFADD__(v29, v28) | __CFADD__(v28, v30);
    v17 = v28 + v30;
    if ( !v3 )
      break;
    v16 >>= 6;
  }
  v31 = a1 >> 1 >= v16;
  if ( a1 >> 1 >= v16 )
  {
    v31 = a1 >= 2 * v16;
    a1 -= 2 * v16;
  }
  return v17 + v31 + v17 + (a1 >= v16) + v17 + v31 + v17;
}

//----- (1FFFF6F6) --------------------------------------------------------
#error "1FFFF70E: positive sp value has been found (funcsize=0)"

//----- (1FFFF740) --------------------------------------------------------
signed int sub_1FFFF740()
{
  return 536870928;
}

//----- (1FFFF748) --------------------------------------------------------
void BKPTduandian_1FFFF748()
{
  __breakpoint(171);
  while ( 1 )
    ;
}

#error "There were 1 decompilation failure(s) on 35 function(s)"
