

;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2015 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-B611-7234-BB			    |
; |		Doskey Lee, Kingsoft Internet Security Software		    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	D28AF59D655C1E179D247F42E6A22531
; Input	CRC32 :	40C36BCC

; File Name   :	E:\stm32 ni xiang\stm32f0boot\boot.bin
; Format      :	Binary file
; Base Address:	0000h Range: 1FFFEC00h - 1FFFFBFFh Loaded length: 0FFFh

; Processor	  : ARM
; ARM architecture: ARMv6-M
; Target assembler: Generic assembler for ARM
; Byte sex	  : Little endian

; ===========================================================================

; Segment type:	Pure code
		AREA ROM, CODE,	READWRITE, ALIGN=0
		; ORG 0x1FFFEC00
		CODE32
dword_1FFFEC00	DCD 0x20000670		; DATA XREF: kanmengou_1FFFECF4+16o
					; ROM:off_1FFFEE2Co
		DCD 0x1FFFEE61
		DCD 0x1FFFECED
		DCD 0x1FFFECED
; ---------------------------------------------------------------------------
		CODE16

loc_1FFFEC10				; CODE XREF: ROM:1FFFEE62j
					; DATA XREF: ROM:1FFFEE60o ...
		BL	loc_1FFFEC18
; ---------------------------------------------------------------------------
		CODE32
		BL	loc_1FFFEC98
; ---------------------------------------------------------------------------
		CODE16

loc_1FFFEC18				; CODE XREF: ROM:loc_1FFFEC10j
		ADR	R0, dword_1FFFEC4C
		LDMIA	R0!, {R4,R5}
		SUBS	R0, #8
		ADDS	R4, R4,	R0
		ADDS	R5, R5,	R0
		MOV	R10, R4
		SUBS	R7, R4,	#1
		MOV	R11, R5
		MOV	R4, R10
		MOV	R5, R11
		CMP	R4, R5
		BNE	loc_1FFFEC34
		BL	loc_1FFFEC98
; ---------------------------------------------------------------------------

loc_1FFFEC34				; CODE XREF: ROM:1FFFEC2Ej
		MOV	R6, PC
		SUBS	R6, #0xF
		LDMIA	R4!, {R0-R3}
		MOV	LR, R6
		MOVS	R6, #1
		TST	R3, R6
		BEQ	loc_1FFFEC44
		SUBS	R3, R7,	R3

loc_1FFFEC44				; CODE XREF: ROM:1FFFEC40j
		MOV	R10, R4
		MOV	R11, R5
		ORRS	R3, R6
		BX	R3
; ---------------------------------------------------------------------------
dword_1FFFEC4C	DCD 0xB1C		; DATA XREF: ROM:loc_1FFFEC18o
					; ROM:1FFFEC1Ao
		DCD 0xB3C
; ---------------------------------------------------------------------------

loc_1FFFEC54				; CODE XREF: ROM:1FFFEC5Cj
		SUBS	R2, #0x10
		BCC	loc_1FFFEC5E
		LDMIA	R0!, {R3-R6}
		STMIA	R1!, {R3-R6}
		BHI	loc_1FFFEC54

loc_1FFFEC5E				; CODE XREF: ROM:1FFFEC56j
		LSLS	R2, R2,	#0x1D
		BCC	loc_1FFFEC66
		LDMIA	R0!, {R4,R5}
		STMIA	R1!, {R4,R5}

loc_1FFFEC66				; CODE XREF: ROM:1FFFEC60j
		BPL	locret_1FFFEC6C
		LDR	R4, [R0]
		STR	R4, [R1]

locret_1FFFEC6C				; CODE XREF: ROM:loc_1FFFEC66j
		BX	LR
; ---------------------------------------------------------------------------
		MOVS	R0, R0
		MOVS	R3, #0
		MOVS	R4, #0
		MOVS	R5, #0
		MOVS	R6, #0

loc_1FFFEC78				; CODE XREF: ROM:1FFFEC7Ej
		SUBS	R2, #0x10
		BCC	loc_1FFFEC80
		STMIA	R1!, {R3-R6}
		BHI	loc_1FFFEC78

loc_1FFFEC80				; CODE XREF: ROM:1FFFEC7Aj
		LSLS	R2, R2,	#0x1D
		BCC	loc_1FFFEC86
		STMIA	R1!, {R4,R5}

loc_1FFFEC86				; CODE XREF: ROM:1FFFEC82j
		BPL	locret_1FFFEC8A
		STR	R3, [R1]

locret_1FFFEC8A				; CODE XREF: ROM:loc_1FFFEC86j
		BX	LR

; =============== S U B	R O U T	I N E =======================================


NOP_1FFFEC8C				; CODE XREF: ROM:1FFFEC9Ep
		PUSH	{R0-R4,LR}
		NOP
		NOP
		POP	{R0-R4,PC}
; End of function NOP_1FFFEC8C


; =============== S U B	R O U T	I N E =======================================


kong_1FFFEC94				; CODE XREF: meiyong_1FFFECAA+2p
		PUSH	{R4,LR}
		POP	{R4,PC}
; End of function kong_1FFFEC94

; ---------------------------------------------------------------------------

loc_1FFFEC98				; CODE XREF: ROM:1FFFEC14j
					; ROM:1FFFEC30j
		BL	sub_1FFFF6F6
		MOV	R1, R2
		BL	NOP_1FFFEC8C
		BL	loc_1FFFEE04
; ---------------------------------------------------------------------------
		BL	loc_1FFFF734

; =============== S U B	R O U T	I N E =======================================

; Attributes: noreturn

meiyong_1FFFECAA			; CODE XREF: ROM:1FFFF73Cp
		PUSH	{R0,R1}
		BL	kong_1FFFEC94
		POP	{R0,R1}
		BL	BKPTduandian_1FFFF748
; End of function meiyong_1FFFECAA

; ---------------------------------------------------------------------------
		MOVS	R0, R0
; ---------------------------------------------------------------------------
byte_1FFFECB8	DCB 0x80		; CODE XREF: ROM:1FFFF37Ep
		DCB 0xF3 ; ó
		DCB    8
		DCB 0x88 ; ˆ
; ---------------------------------------------------------------------------
		BX	LR

; =============== S U B	R O U T	I N E =======================================


guanzhongduan_1FFFECBE			; CODE XREF: ROM:loc_1FFFEE04p
					; sub_1FFFF172+2p
		CPSID	I
		BX	LR
; End of function guanzhongduan_1FFFECBE


; =============== S U B	R O U T	I N E =======================================


kaizhongduan_1FFFECC2			; CODE XREF: ROM:1FFFF376p
		CPSIE	I
		BX	LR
; End of function kaizhongduan_1FFFECC2

; ---------------------------------------------------------------------------
		DCB    0
		DCB    0

; =============== S U B	R O U T	I N E =======================================


systick_1FFFECC8			; CODE XREF: kanmengou_1FFFECF4:loc_1FFFED34p
					; kanmengou_1FFFECF4+C2p ...
		LDR	R0, =0xE000E000
		MOVS	R1, #0
		STR	R1, [R0,#0x10]
		STR	R1, [R0,#0x18]
		MOVS	R1, #0x80000
		STR	R1, [R0,#0x14]
		BX	LR
; End of function systick_1FFFECC8


; =============== S U B	R O U T	I N E =======================================


fuwei_1FFFECD8				; CODE XREF: ROM:1FFFECEEp
					; ROM:1FFFEE10p ...
		LDR	R1, =0xE000ED00
		LDR	R0, =0x5FA0004
		STR	R0, [R1,#0xC]
		BX	LR
; End of function fuwei_1FFFECD8

; ---------------------------------------------------------------------------
dword_1FFFECE0	DCD 0xE000E000		; DATA XREF: systick_1FFFECC8r
dword_1FFFECE4	DCD 0x5FA0004		; DATA XREF: fuwei_1FFFECD8+2r
dword_1FFFECE8	DCD 0xE000ED00		; DATA XREF: fuwei_1FFFECD8r
; ---------------------------------------------------------------------------
		PUSH	{R4,LR}
		BL	fuwei_1FFFECD8
		POP	{R4,PC}

; =============== S U B	R O U T	I N E =======================================


kanmengou_1FFFECF4			; CODE XREF: ROM:1FFFEE08p
		PUSH	{R3-R7,LR}
		LDR	R0, =0x40003000
		LDR	R1, =0x5555
		STR	R1, [R0]
		MOVS	R1, #6
		STR	R1, [R0,#4]
		LDR	R1, =0xAAAA
		STR	R1, [R0]
		BL	sub_1FFFEECC
		LDR	R1, =0xE000ED00
		LDR	R0, =dword_1FFFEC00
		STR	R0, [R1,#8]
		BL	jiancedubaohu_1FFFF124 ; ¼ì²â¶Á±£»¤
		LDR	R4, =0x20000004
		MOVS	R5, #0
		CMP	R0, #1
		BNE	loc_1FFFED34
		LDR	R0, =0x20000FFC
		STR	R0, [R4]
		LDR	R0, =0x20000800
		B	loc_1FFFED2C
; ---------------------------------------------------------------------------

loc_1FFFED22				; CODE XREF: kanmengou_1FFFECF4+3Cj
		LDR	R1, [R4]
		STR	R5, [R1]
		LDR	R1, [R4]
		SUBS	R1, R1,	#4
		STR	R1, [R4]

loc_1FFFED2C				; CODE XREF: kanmengou_1FFFECF4+2Cj
		LDR	R1, [R4]
		CMP	R1, R0
		BCS	loc_1FFFED22
		STR	R5, [R4]

loc_1FFFED34				; CODE XREF: kanmengou_1FFFECF4+24j
		BL	systick_1FFFECC8
		LDR	R6, =0xE000E000
		MOVS	R0, #4
		STR	R0, [R6,#0x10]
		LSLS	R7, R0,	#0x11
		STR	R7, [R6,#0x14]
		LSLS	R1, R0,	#0xC
		LDR	R0, =0x40021000
		STR	R1, [R0,#0x18]
		LDR	R1, =0x20014
		STR	R1, [R0,#0x14]
		BL	FPECjiesuo_1FFFEF62 ; FPEC½âËø
		MOVS	R0, #9
		LDR	R1, =0x28080000
		LSLS	R0, R0,	#0x1B
		STR	R1, [R0]
		MOVS	R1, #0
		STRH	R1, [R0,#4]
		LDR	R2, =0xFC3C0000
		STR	R2, [R0,#8]
		LDR	R2, =0x54140000
		STR	R2, [R0,#0xC]
		STR	R1, [R0,#0x24]
		MOV	R5, R0

loc_1FFFED68				; CODE XREF: kanmengou_1FFFECF4+CAj
					; kanmengou_1FFFECF4+D0j ...
		LDRH	R0, [R5,#0x10]
		LSLS	R0, R0,	#0x15
		BMI	loc_1FFFED72
		MOVS	R0, #1
		STR	R0, [R4,#4]

loc_1FFFED72				; CODE XREF: kanmengou_1FFFECF4+78j
		LDRH	R0, [R5,#0x10]
		LSRS	R0, R0,	#0xF
		BNE	loc_1FFFED7C
		MOVS	R0, #1
		STR	R0, [R4,#8]

loc_1FFFED7C				; CODE XREF: kanmengou_1FFFECF4+82j
		LDR	R0, [R4,#4]
		CMP	R0, #1
		BNE	loc_1FFFEDBA
		LDRH	R0, [R5,#0x10]
		LSLS	R0, R0,	#0x15
		BPL	loc_1FFFEDBA
		MOVS	R0, #5
		STR	R0, [R6,#0x10]
		LDR	R0, =0x5FFF
		B	loc_1FFFED92
; ---------------------------------------------------------------------------

loc_1FFFED90				; CODE XREF: kanmengou_1FFFECF4+A6j
		SUBS	R0, R0,	#1

loc_1FFFED92				; CODE XREF: kanmengou_1FFFECF4+9Aj
		LDRH	R1, [R5,#0x10]
		LSLS	R1, R1,	#0x15
		BPL	loc_1FFFED9E
		CMP	R0, #0
		BNE	loc_1FFFED90
		B	loc_1FFFEDB2
; ---------------------------------------------------------------------------

loc_1FFFED9E				; CODE XREF: kanmengou_1FFFECF4+A2j
		CMP	R0, #0
		BEQ	loc_1FFFEDB2
		LDR	R0, [R6,#0x18]
		SUBS	R0, R7,	R0
		STR	R0, [R4]
		LDR	R0, =0x28280000
		STR	R0, [R5]
		MOVS	R0, #0x110
		B	loc_1FFFEDF0
; ---------------------------------------------------------------------------

loc_1FFFEDB2				; CODE XREF: kanmengou_1FFFECF4+A8j
					; kanmengou_1FFFECF4+ACj
		MOVS	R0, #0
		STR	R0, [R4,#4]
		BL	systick_1FFFECC8

loc_1FFFEDBA				; CODE XREF: kanmengou_1FFFECF4+8Cj
					; kanmengou_1FFFECF4+92j
		LDR	R0, [R4,#8]
		CMP	R0, #1
		BNE	loc_1FFFED68
		LDRH	R0, [R5,#0x10]
		LSRS	R0, R0,	#0xF
		BEQ	loc_1FFFED68
		MOVS	R0, #5
		STR	R0, [R6,#0x10]
		LDR	R0, =0x5FFF
		B	loc_1FFFEDD0
; ---------------------------------------------------------------------------

loc_1FFFEDCE				; CODE XREF: kanmengou_1FFFECF4+E4j
		SUBS	R0, R0,	#1

loc_1FFFEDD0				; CODE XREF: kanmengou_1FFFECF4+D8j
		LDRH	R1, [R5,#0x10]
		LSRS	R1, R1,	#0xF
		BEQ	loc_1FFFEDDC
		CMP	R0, #0
		BNE	loc_1FFFEDCE
		B	loc_1FFFEDFA
; ---------------------------------------------------------------------------

loc_1FFFEDDC				; CODE XREF: kanmengou_1FFFECF4+E0j
		CMP	R0, #0
		BEQ	loc_1FFFEDFA
		LDR	R0, [R6,#0x18]
		SUBS	R0, R7,	R0
		STR	R0, [R4]
		MOVS	R0, #0xA8000000
		STR	R0, [R5]
		MOVS	R0, #0x11000000

loc_1FFFEDF0				; CODE XREF: kanmengou_1FFFECF4+BCj
		STR	R0, [R5,#0x24]
		BL	systick_1FFFECC8
		MOVS	R0, #1
		POP	{R3-R7,PC}
; ---------------------------------------------------------------------------

loc_1FFFEDFA				; CODE XREF: kanmengou_1FFFECF4+E6j
					; kanmengou_1FFFECF4+EAj
		MOVS	R0, #0
		STR	R0, [R4,#8]
		BL	systick_1FFFECC8
		B	loc_1FFFED68
; End of function kanmengou_1FFFECF4

; ---------------------------------------------------------------------------

loc_1FFFEE04				; CODE XREF: ROM:1FFFECA2j
		BL	guanzhongduan_1FFFECBE
		BL	kanmengou_1FFFECF4
		CMP	R0, #1
		BEQ	loc_1FFFEE16
		BL	fuwei_1FFFECD8

loc_1FFFEE14				; CODE XREF: ROM:loc_1FFFEE14j
					; ROM:1FFFEE1Ej
		B	loc_1FFFEE14
; ---------------------------------------------------------------------------

loc_1FFFEE16				; CODE XREF: ROM:1FFFEE0Ej
		BL	sub_1FFFF172
		BL	loc_1FFFF280
; ---------------------------------------------------------------------------
		B	loc_1FFFEE14
; ---------------------------------------------------------------------------
		DCD 0x5555		; DATA XREF: kanmengou_1FFFECF4+4r
dword_1FFFEE24	DCD 0x40003000		; DATA XREF: kanmengou_1FFFECF4+2r
dword_1FFFEE28	DCD 0xAAAA		; DATA XREF: kanmengou_1FFFECF4+Cr
off_1FFFEE2C	DCD dword_1FFFEC00	; DATA XREF: kanmengou_1FFFECF4+16r
dword_1FFFEE30	DCD 0xE000ED00		; DATA XREF: kanmengou_1FFFECF4+14r
dword_1FFFEE34	DCD 0x20000004		; DATA XREF: kanmengou_1FFFECF4+1Er
dword_1FFFEE38	DCD 0x20000FFC		; DATA XREF: kanmengou_1FFFECF4+26r
dword_1FFFEE3C	DCD 0x20000800		; DATA XREF: kanmengou_1FFFECF4+2Ar
dword_1FFFEE40	DCD 0xE000E000		; DATA XREF: kanmengou_1FFFECF4+44r
dword_1FFFEE44	DCD 0x40021000		; DATA XREF: kanmengou_1FFFECF4+50r
dword_1FFFEE48	DCD 0x20014		; DATA XREF: kanmengou_1FFFECF4+54r
dword_1FFFEE4C	DCD 0x28080000		; DATA XREF: kanmengou_1FFFECF4+5Er
dword_1FFFEE50	DCD 0xFC3C0000		; DATA XREF: kanmengou_1FFFECF4+68r
dword_1FFFEE54	DCD 0x54140000		; DATA XREF: kanmengou_1FFFECF4+6Cr
dword_1FFFEE58	DCD 0x5FFF		; DATA XREF: kanmengou_1FFFECF4+98r
					; kanmengou_1FFFECF4+D6r
dword_1FFFEE5C	DCD 0x28280000		; DATA XREF: kanmengou_1FFFECF4+B4r
; ---------------------------------------------------------------------------
		LDR	R0, =(loc_1FFFEC10+1)
		BX	R0 ; loc_1FFFEC10

; =============== S U B	R O U T	I N E =======================================


sub_1FFFEE64				; CODE XREF: sub_1FFFF6F6+18p
		LDR	R0, =0x20000070
		LDR	R1, =0x20000670
		LDR	R2, =0x20000270
		LDR	R3, =0x20000270
		BX	LR
; End of function sub_1FFFEE64

; ---------------------------------------------------------------------------
		DCB 0
		DCB 0
off_1FFFEE70	DCD loc_1FFFEC10+1	; DATA XREF: ROM:1FFFEE60r
dword_1FFFEE74	DCD 0x20000070		; DATA XREF: sub_1FFFEE64r
dword_1FFFEE78	DCD 0x20000670		; DATA XREF: sub_1FFFEE64+2r
dword_1FFFEE7C	DCD 0x20000270		; DATA XREF: sub_1FFFEE64+4r
dword_1FFFEE80	DCD 0x20000270		; DATA XREF: sub_1FFFEE64+6r

; =============== S U B	R O U T	I N E =======================================


RCCshizhong_1FFFEE84			; CODE XREF: qingchuRCC_1FFFEEA8+2p
					; sub_1FFFEECC+4p
		LDR	R0, =0x40021000
		LDR	R1, [R0]
		MOVS	R2, #1
		ORRS	R1, R2
		STR	R1, [R0]
		MOVS	R1, #0
		STRH	R1, [R0,#4]
		STRB	R1, [R0,#7]
		STRH	R1, [R0,#2]
		STRB	R1, [R0,#6]
		LDR	R2, =0x40021000
		ADDS	R2, #0x20
		STRB	R1, [R2,#0xC]
		STRH	R1, [R2,#0x10]
		MOVS	R3, #0x80
		STRB	R3, [R2,#0x14]
		STR	R1, [R0,#8]
		BX	LR
; End of function RCCshizhong_1FFFEE84


; =============== S U B	R O U T	I N E =======================================


qingchuRCC_1FFFEEA8			; CODE XREF: ROM:loc_1FFFF372p
		PUSH	{LR}
		BL	RCCshizhong_1FFFEE84
		MOVS	R2, #0
		LDR	R0, =0x40021000
		MVNS	R2, R2
		STR	R2, [R0,#0xC]
		MOVS	R1, #0
		STR	R1, [R0,#0xC]
		STR	R2, [R0,#0x10]
		STR	R1, [R0,#0x10]
		STR	R2, [R0,#0x28]
		STR	R1, [R0,#0x28]
		STR	R1, [R0,#0x18]
		STR	R1, [R0,#0x1C]
		MOVS	R1, #0x14
		STR	R1, [R0,#0x14]
		POP	{PC}
; End of function qingchuRCC_1FFFEEA8


; =============== S U B	R O U T	I N E =======================================


sub_1FFFEECC				; CODE XREF: kanmengou_1FFFECF4+10p
		PUSH	{R4-R6,LR}
		LDR	R4, =0x1FFFF
		BL	RCCshizhong_1FFFEE84
		LDR	R1, =0x40022000
		MOVS	R0, #0
		STR	R0, [R1]
		LDR	R5, =0x40021000
		MOVS	R0, #0x10
		STRB	R0, [R5,#6]
		MOVS	R0, #1
		STRB	R0, [R5,#3]
		B	loc_1FFFEEE8
; ---------------------------------------------------------------------------

loc_1FFFEEE6				; CODE XREF: sub_1FFFEECC+24j
		SUBS	R4, R4,	#1

loc_1FFFEEE8				; CODE XREF: sub_1FFFEECC+18j
		LDRB	R0, [R5,#3]
		CMP	R0, #3
		BEQ	loc_1FFFEEF4
		CMP	R4, #0
		BNE	loc_1FFFEEE6
		B	loc_1FFFEEF8
; ---------------------------------------------------------------------------

loc_1FFFEEF4				; CODE XREF: sub_1FFFEECC+20j
		CMP	R4, #0
		BNE	loc_1FFFEEFC

loc_1FFFEEF8				; CODE XREF: sub_1FFFEECC+26j
		BL	fuwei_1FFFECD8

loc_1FFFEEFC				; CODE XREF: sub_1FFFEECC+2Aj
		MOVS	R0, #2
		STRB	R0, [R5,#4]
		POP	{R4-R6,PC}
; End of function sub_1FFFEECC

; ---------------------------------------------------------------------------
		DCB    0
		DCB    0
dword_1FFFEF04	DCD 0x40021000		; DATA XREF: RCCshizhong_1FFFEE84r
					; RCCshizhong_1FFFEE84+14r ...
dword_1FFFEF08	DCD 0x1FFFF		; DATA XREF: sub_1FFFEECC+2r
dword_1FFFEF0C	DCD 0x40022000		; DATA XREF: sub_1FFFEECC+8r

; =============== S U B	R O U T	I N E =======================================


sub_1FFFEF10				; CODE XREF: ROM:1FFFF328p
					; ROM:1FFFF364p ...
		MOVS	R1, #0xF8000000
		MOVS	R2, #1
		ADDS	R1, R0,	R1
		LSLS	R2, R2,	#0xF
		CMP	R1, R2
		BCS	loc_1FFFEF22
		MOVS	R0, #2
		BX	LR
; ---------------------------------------------------------------------------

loc_1FFFEF22				; CODE XREF: sub_1FFFEF10+Cj
		LDR	R1, =0xDFFFF800
		MOVS	R2, #1
		ADDS	R1, R0,	R1
		LSLS	R2, R2,	#0xB
		CMP	R1, R2
		BCS	loc_1FFFEF32
		MOVS	R0, #3
		BX	LR
; ---------------------------------------------------------------------------

loc_1FFFEF32				; CODE XREF: sub_1FFFEF10+1Cj
		LDR	R1, =0xE0000800
		ADDS	R1, R0,	R1
		CMP	R1, #0xF
		BCS	loc_1FFFEF3E
		MOVS	R0, #4
		BX	LR
; ---------------------------------------------------------------------------

loc_1FFFEF3E				; CODE XREF: sub_1FFFEF10+28j
		LDR	R1, =0xE0001400
		ADDS	R0, R0,	R1
		LDR	R1, =0xBFF
		CMP	R0, R1
		BCS	loc_1FFFEF4C
		MOVS	R0, #5
		BX	LR
; ---------------------------------------------------------------------------

loc_1FFFEF4C				; CODE XREF: sub_1FFFEF10+36j
		MOVS	R0, #1
		BX	LR
; End of function sub_1FFFEF10


; =============== S U B	R O U T	I N E =======================================


sub_1FFFEF50				; CODE XREF: ROM:1FFFF590p
		LDR	R0, =0x20000FFC
		MOVS	R2, #0
		MOVS	R1, #0x20000000

loc_1FFFEF58				; CODE XREF: sub_1FFFEF50+Ej
		STR	R2, [R0]
		SUBS	R0, R0,	#4
		CMP	R0, R1
		BNE	loc_1FFFEF58
		BX	LR
; End of function sub_1FFFEF50


; =============== S U B	R O U T	I N E =======================================

; FPEC½âËø

FPECjiesuo_1FFFEF62			; CODE XREF: kanmengou_1FFFECF4+58p
					; zijiebiancheng_1FFFF048+18p ...
		LDR	R0, =0x40022000
		LDR	R1, =0x45670123
		STR	R1, [R0,#4]
		LDR	R1, =0xCDEF89AB
		STR	R1, [R0,#4]
		BX	LR
; End of function FPECjiesuo_1FFFEF62


; =============== S U B	R O U T	I N E =======================================

; OPTWRE½âËø

OPTWREjiesuo_1FFFEF6E			; CODE XREF: zhengpian_1FFFEFF8+2p
					; xuanzezijiecachu_1FFFF020+2p	...
		LDR	R0, =0x40022000
		LDR	R1, =0x45670123
		STR	R1, [R0,#8]
		LDR	R1, =0xCDEF89AB
		STR	R1, [R0,#8]
		BX	LR
; End of function OPTWREjiesuo_1FFFEF6E


; =============== S U B	R O U T	I N E =======================================

; flash	Ã¦

flashmang_1FFFEF7A			; CODE XREF: xieflash_1FFFEF9A+6p
					; xieflash_1FFFEF9A+16p ...
		PUSH	{R4,LR}
		LDR	R0, =0xFFF
		LDR	R1, =0x40022000
		B	loc_1FFFEF84
; ---------------------------------------------------------------------------

loc_1FFFEF82				; CODE XREF: flashmang_1FFFEF7A+12j
		SUBS	R0, R0,	#1

loc_1FFFEF84				; CODE XREF: flashmang_1FFFEF7A+6j
		LDR	R2, [R1,#0xC]
		LSLS	R2, R2,	#0x1F
		BEQ	loc_1FFFEF90
		CMP	R0, #0
		BNE	loc_1FFFEF82
		B	loc_1FFFEF94
; ---------------------------------------------------------------------------

loc_1FFFEF90				; CODE XREF: flashmang_1FFFEF7A+Ej
		CMP	R0, #0
		BNE	locret_1FFFEF98

loc_1FFFEF94				; CODE XREF: flashmang_1FFFEF7A+14j
		BL	fuwei_1FFFECD8

locret_1FFFEF98				; CODE XREF: flashmang_1FFFEF7A+18j
		POP	{R4,PC}
; End of function flashmang_1FFFEF7A


; =============== S U B	R O U T	I N E =======================================

; ±à³Ì

xieflash_1FFFEF9A			; CODE XREF: ROM:1FFFF3DEp
		PUSH	{R4-R6,LR}
		MOV	R6, R0
		MOV	R5, R1
		BL	flashmang_1FFFEF7A ; flash Ã¦
		LDR	R4, =0x40022000
		LDR	R0, [R4,#0x10]
		MOVS	R1, #1
		ORRS	R0, R1
		STR	R0, [R4,#0x10]
		STRH	R5, [R6]
		BL	flashmang_1FFFEF7A ; flash Ã¦
		LDR	R0, [R4,#0xC]
		LSLS	R0, R0,	#0x1D
		BMI	loc_1FFFEFC2
		LSRS	R0, R5,	#0x10
		STRH	R0, [R6,#2]
		BL	flashmang_1FFFEF7A ; flash Ã¦

loc_1FFFEFC2				; CODE XREF: xieflash_1FFFEF9A+1Ej
		LDR	R0, [R4,#0xC]
		LSLS	R0, R0,	#0x1D
		BPL	loc_1FFFEFD0
		LDR	R0, [R4,#0xC]
		MOVS	R1, #4
		ORRS	R0, R1
		STR	R0, [R4,#0xC]

loc_1FFFEFD0				; CODE XREF: xieflash_1FFFEF9A+2Cj
		LDR	R0, [R4,#0x10]
		LSRS	R0, R0,	#1
		LSLS	R0, R0,	#1
		STR	R0, [R4,#0x10]
		POP	{R4-R6,PC}
; End of function xieflash_1FFFEF9A


; =============== S U B	R O U T	I N E =======================================

; Ò³²Á³ý

yecachu_1FFFEFDA			; CODE XREF: ROM:1FFFF4C6p
		PUSH	{R4-R6,LR}
		MOV	R5, R0
		BL	flashmang_1FFFEF7A ; flash Ã¦
		LDR	R4, =0x40022000
		MOVS	R0, #2
		STR	R0, [R4,#0x10]
		STR	R5, [R4,#0x14]
		MOVS	R0, #0x42
		STR	R0, [R4,#0x10]
		BL	flashmang_1FFFEF7A ; flash Ã¦
		MOVS	R0, #0
		STR	R0, [R4,#0x10]
		POP	{R4-R6,PC}
; End of function yecachu_1FFFEFDA


; =============== S U B	R O U T	I N E =======================================

; ÕûÆ¬²Á³ý

zhengpian_1FFFEFF8			; CODE XREF: ROM:loc_1FFFF49Ap
		PUSH	{R4-R6,LR}
		BL	OPTWREjiesuo_1FFFEF6E ;	OPTWRE½âËø
		BL	flashmang_1FFFEF7A ; flash Ã¦
		LDR	R4, =0x40022000
		LDR	R0, [R4,#0x10]
		MOVS	R5, #4
		ORRS	R0, R5
		STR	R0, [R4,#0x10]
		LDR	R0, [R4,#0x10]
		MOVS	R1, #0x40
		ORRS	R0, R1
		STR	R0, [R4,#0x10]
		BL	flashmang_1FFFEF7A ; flash Ã¦
		LDR	R0, [R4,#0x10]
		BICS	R0, R5
		STR	R0, [R4,#0x10]
		POP	{R4-R6,PC}
; End of function zhengpian_1FFFEFF8


; =============== S U B	R O U T	I N E =======================================

; Ñ¡Ïî×Ö½Ú²Á³ý

xuanzezijiecachu_1FFFF020		; CODE XREF: zijiebiancheng_1FFFF048+14p
					; xiebaohu_1FFFF0A6+1Ap ...
		PUSH	{R4-R6,LR}
		BL	OPTWREjiesuo_1FFFEF6E ;	OPTWRE½âËø
		BL	flashmang_1FFFEF7A ; flash Ã¦
		LDR	R4, =0x40022000
		LDR	R0, [R4,#0x10]
		MOVS	R5, #0x20
		ORRS	R0, R5
		STR	R0, [R4,#0x10]
		LDR	R0, [R4,#0x10]
		MOVS	R1, #0x40
		ORRS	R0, R1
		STR	R0, [R4,#0x10]
		BL	flashmang_1FFFEF7A ; flash Ã¦
		LDR	R0, [R4,#0x10]
		BICS	R0, R5
		STR	R0, [R4,#0x10]
		POP	{R4-R6,PC}
; End of function xuanzezijiecachu_1FFFF020


; =============== S U B	R O U T	I N E =======================================

; ×Ö½Ú±à³Ì

zijiebiancheng_1FFFF048			; CODE XREF: ROM:1FFFF514p

var_18		= -0x18

		PUSH	{R3-R7,LR}
		LDR	R4, =0xE0000800
		NEGS	R4, R4
		LDRH	R7, [R4]
		LDRH	R1, [R4,#(word_1FFFF802	- 0x1FFFF800)]
		MVNS	R0, R0
		UXTB	R5, R0
		LSLS	R0, R0,	#0x10
		LSRS	R6, R0,	#0x18
		STR	R1, [SP,#0x18+var_18]
		BL	xuanzezijiecachu_1FFFF020 ; Ñ¡Ïî×Ö½Ú²Á³ý
		BL	FPECjiesuo_1FFFEF62 ; FPEC½âËø
		BL	OPTWREjiesuo_1FFFEF6E ;	OPTWRE½âËø
		LDR	R0, =0x40022000
		LDR	R1, [R0,#0x10]
		MOVS	R2, #0x10
		ORRS	R1, R2
		STR	R1, [R0,#0x10]
		UXTB	R0, R7
		STRH	R0, [R4]
		BL	flashmang_1FFFEF7A ; flash Ã¦
		LDR	R1, [SP,#0x18+var_18]
		UXTB	R0, R1
		STRH	R0, [R4,#(word_1FFFF802	- 0x1FFFF800)]
		BL	flashmang_1FFFEF7A ; flash Ã¦
		CMP	R5, #0xFF
		BEQ	loc_1FFFF08E
		STRH	R5, [R4,#(word_1FFFF808	- 0x1FFFF800)]
		BL	flashmang_1FFFEF7A ; flash Ã¦

loc_1FFFF08E				; CODE XREF: zijiebiancheng_1FFFF048+3Ej
		CMP	R6, #0xFF
		BEQ	loc_1FFFF098
		STRH	R6, [R4,#(word_1FFFF80A	- 0x1FFFF800)]
		BL	flashmang_1FFFEF7A ; flash Ã¦

loc_1FFFF098				; CODE XREF: zijiebiancheng_1FFFF048+48j
		LDR	R0, =0x40022000
		LDR	R2, [R0,#0x10]
		MOVS	R1, #0x10
		BICS	R2, R1
		STR	R2, [R0,#0x10]
		POP	{R3-R7,PC}
; End of function zijiebiancheng_1FFFF048

; ---------------------------------------------------------------------------
		DCB 0x70 ; p
		DCB 0x47 ; G

; =============== S U B	R O U T	I N E =======================================

; Ð´±£»¤

xiebaohu_1FFFF0A6			; CODE XREF: ROM:loc_1FFFF544p
					; ROM:1FFFF586p

var_20		= -0x20
var_1C		= -0x1C
var_18		= -0x18

		PUSH	{R0,R4-R7,LR}
		SUB	SP, SP,	#8
		BL	flashmang_1FFFEF7A ; flash Ã¦
		LDR	R4, =0xE0000800
		NEGS	R4, R4
		LDRH	R7, [R4,#(word_1FFFF802	- 0x1FFFF800)]
		LDRH	R5, [R4,#(word_1FFFF804	- 0x1FFFF800)]
		LDRH	R6, [R4,#(word_1FFFF806	- 0x1FFFF800)]
		LDRH	R0, [R4,#(word_1FFFF808	- 0x1FFFF800)]
		STR	R0, [SP,#0x20+var_20]
		LDRH	R0, [R4,#(word_1FFFF80A	- 0x1FFFF800)]
		STR	R0, [SP,#0x20+var_1C]
		BL	xuanzezijiecachu_1FFFF020 ; Ñ¡Ïî×Ö½Ú²Á³ý
		BL	FPECjiesuo_1FFFEF62 ; FPEC½âËø
		BL	OPTWREjiesuo_1FFFEF6E ;	OPTWRE½âËø
		BL	flashmang_1FFFEF7A ; flash Ã¦
		LDR	R0, =0x40022000
		LDR	R1, [R0,#0x10]
		MOVS	R2, #0x10
		ORRS	R1, R2
		STR	R1, [R0,#0x10]
		LDR	R0, [SP,#0x20+var_18]
		CMP	R0, #0
		BEQ	loc_1FFFF110
		UXTB	R0, R7
		STRH	R0, [R4,#(word_1FFFF802	- 0x1FFFF800)]
		BL	flashmang_1FFFEF7A ; flash Ã¦
		UXTB	R0, R5
		STRH	R0, [R4,#(word_1FFFF804	- 0x1FFFF800)]
		BL	flashmang_1FFFEF7A ; flash Ã¦
		UXTB	R0, R6
		STRH	R0, [R4,#(word_1FFFF806	- 0x1FFFF800)]
		BL	flashmang_1FFFEF7A ; flash Ã¦
		LDR	R0, [SP,#0x20+var_20]
		UXTB	R0, R0
		STRH	R0, [R4,#(word_1FFFF808	- 0x1FFFF800)]
		BL	flashmang_1FFFEF7A ; flash Ã¦
		LDR	R0, [SP,#0x20+var_1C]
		UXTB	R0, R0
		STRH	R0, [R4,#(word_1FFFF808	- 0x1FFFF800)]
		BL	flashmang_1FFFEF7A ; flash Ã¦
		MOVS	R0, #0
		B	loc_1FFFF112
; ---------------------------------------------------------------------------

loc_1FFFF110				; CODE XREF: xiebaohu_1FFFF0A6+38j
		MOVS	R0, #0xAA

loc_1FFFF112				; CODE XREF: xiebaohu_1FFFF0A6+68j
		STRH	R0, [R4]
		BL	flashmang_1FFFEF7A ; flash Ã¦
		LDR	R0, =0x40022000
		LDR	R2, [R0,#0x10]
		MOVS	R1, #0x10
		BICS	R2, R1
		STR	R2, [R0,#0x10]
		POP	{R1-R7,PC}
; End of function xiebaohu_1FFFF0A6


; =============== S U B	R O U T	I N E =======================================

; ¼ì²â¶Á±£»¤

jiancedubaohu_1FFFF124			; CODE XREF: kanmengou_1FFFECF4+1Ap
					; sub_1FFFF22E+2p ...
		LDR	R1, =0x40022000
		MOVS	R0, #0
		LDR	R1, [R1,#0x1C]
		LSLS	R1, R1,	#0x1E
		BPL	locret_1FFFF130
		MOVS	R0, #1

locret_1FFFF130				; CODE XREF: jiancedubaohu_1FFFF124+8j
		BX	LR
; End of function jiancedubaohu_1FFFF124


; =============== S U B	R O U T	I N E =======================================

; Ñ¡Ïî×Ö½ÚÇ¿ÖÆ¸üÐÂ

xuanzezijieqiangzhigengxin_1FFFF132	; CODE XREF: ROM:1FFFF45Ap
					; ROM:loc_1FFFF578p
		LDR	R0, =0x40022000
		LDR	R1, [R0,#0x10]
		MOVS	R2, #0x2000
		ORRS	R1, R2
		STR	R1, [R0,#0x10]
		BX	LR
; End of function xuanzezijieqiangzhigengxin_1FFFF132

; ---------------------------------------------------------------------------
dword_1FFFF140	DCD 0xDFFFF800		; DATA XREF: sub_1FFFEF10:loc_1FFFEF22r
dword_1FFFF144	DCD 0xE0000800		; DATA XREF: sub_1FFFEF10:loc_1FFFEF32r
					; zijiebiancheng_1FFFF048+2r ...
dword_1FFFF148	DCD 0xE0001400		; DATA XREF: sub_1FFFEF10:loc_1FFFEF3Er
dword_1FFFF14C	DCD 0xBFF		; DATA XREF: sub_1FFFEF10+32r
dword_1FFFF150	DCD 0x20000FFC		; DATA XREF: sub_1FFFEF50r
dword_1FFFF154	DCD 0x45670123		; DATA XREF: FPECjiesuo_1FFFEF62+2r
					; OPTWREjiesuo_1FFFEF6E+2r
dword_1FFFF158	DCD 0x40022000		; DATA XREF: FPECjiesuo_1FFFEF62r
					; OPTWREjiesuo_1FFFEF6Er ...
dword_1FFFF15C	DCD 0xCDEF89AB		; DATA XREF: FPECjiesuo_1FFFEF62+6r
					; OPTWREjiesuo_1FFFEF6E+6r
dword_1FFFF160	DCD 0xFFF		; DATA XREF: flashmang_1FFFEF7A+2r

; =============== S U B	R O U T	I N E =======================================


sub_1FFFF164				; CODE XREF: sub_1FFFF172+1Cp
					; sub_1FFFF1B2+22p ...
		LDR	R1, =0x20000000
		LDR	R1, [R1]
		STRH	R0, [R1,#0x28]

loc_1FFFF16A				; CODE XREF: sub_1FFFF164+Aj
		LDR	R0, [R1,#0x1C]
		LSLS	R0, R0,	#0x19
		BPL	loc_1FFFF16A
		BX	LR
; End of function sub_1FFFF164


; =============== S U B	R O U T	I N E =======================================


sub_1FFFF172				; CODE XREF: ROM:loc_1FFFEE16p
		PUSH	{R4,LR}
		BL	guanzhongduan_1FFFECBE
		LDR	R4, =0x20000004
		MOVS	R1, #7
		LDR	R0, [R4]
		BL	sub_1FFFF596
		LDR	R2, =0x20000000
		LDR	R1, [R2]
		STRH	R0, [R1,#0xC]
		LDR	R0, =0x140D
		STR	R0, [R1]
		MOVS	R0, #0x79
		BL	sub_1FFFF164
		LDR	R0, [R2]
		LDRH	R0, [R0,#0x24]
		STR	R0, [R4]
		POP	{R4,PC}
; End of function sub_1FFFF172


; =============== S U B	R O U T	I N E =======================================


weigou_1FFFF19A				; CODE XREF: sub_1FFFF1B2:loc_1FFFF1BCp
					; sub_1FFFF1B2:loc_1FFFF1CAp ...
		LDR	R0, =0x20000000
		LDR	R1, =0xAAAA
		LDR	R0, [R0]
		LDR	R2, =0x40003000
		B	loc_1FFFF1A6
; ---------------------------------------------------------------------------

loc_1FFFF1A4				; CODE XREF: weigou_1FFFF19A+10j
		STR	R1, [R2]

loc_1FFFF1A6				; CODE XREF: weigou_1FFFF19A+8j
		LDR	R3, [R0,#0x1C]
		LSLS	R3, R3,	#0x1A
		BPL	loc_1FFFF1A4
		LDRH	R0, [R0,#0x24]
		UXTB	R0, R0
		BX	LR
; End of function weigou_1FFFF19A


; =============== S U B	R O U T	I N E =======================================


sub_1FFFF1B2				; CODE XREF: ROM:1FFFF3AAp
					; ROM:1FFFF4ECp
		PUSH	{R4-R6,LR}
		MOV	R6, R1
		ADDS	R5, R0,	#1
		MOV	R4, R0
		BEQ	loc_1FFFF1CA

loc_1FFFF1BC				; CODE XREF: sub_1FFFF1B2+16j
		BL	weigou_1FFFF19A
		EORS	R4, R0
		STRB	R0, [R6]
		ADDS	R6, R6,	#1
		SUBS	R5, R5,	#1
		BNE	loc_1FFFF1BC

loc_1FFFF1CA				; CODE XREF: sub_1FFFF1B2+8j
		BL	weigou_1FFFF19A
		CMP	R0, R4
		BEQ	loc_1FFFF1DC
		MOVS	R0, #0x1F
		BL	sub_1FFFF164
		MOVS	R0, #0x55
		POP	{R4-R6,PC}
; ---------------------------------------------------------------------------

loc_1FFFF1DC				; CODE XREF: sub_1FFFF1B2+1Ej
		MOVS	R0, #0xAA
		POP	{R4-R6,PC}
; End of function sub_1FFFF1B2


; =============== S U B	R O U T	I N E =======================================


sub_1FFFF1E0				; CODE XREF: ROM:1FFFF4B0p
		PUSH	{R4-R7,LR}
		MOV	R6, R1
		ADDS	R5, R0,	#1
		LSRS	R1, R0,	#8
		UXTB	R7, R0
		EORS	R7, R1
		MOVS	R4, R5
		BEQ	loc_1FFFF218

loc_1FFFF1F0				; CODE XREF: sub_1FFFF1E0+36j
		BL	weigou_1FFFF19A
		EORS	R7, R0
		MOV	R12, R7
		LSLS	R7, R0,	#8
		BL	weigou_1FFFF19A
		ORRS	R0, R7
		UXTB	R1, R0
		MOV	R7, R12
		EORS	R7, R1
		MOVS	R1, #1
		SUBS	R2, R5,	R4
		LSLS	R1, R1,	#0xA
		CMP	R2, R1
		BCS	loc_1FFFF214
		STRH	R0, [R6]
		ADDS	R6, R6,	#2

loc_1FFFF214				; CODE XREF: sub_1FFFF1E0+2Ej
		SUBS	R4, R4,	#1
		BNE	loc_1FFFF1F0

loc_1FFFF218				; CODE XREF: sub_1FFFF1E0+Ej
		BL	weigou_1FFFF19A
		CMP	R0, R7
		BEQ	loc_1FFFF22A
		MOVS	R0, #0x1F
		BL	sub_1FFFF164
		MOVS	R0, #0x55
		POP	{R4-R7,PC}
; ---------------------------------------------------------------------------

loc_1FFFF22A				; CODE XREF: sub_1FFFF1E0+3Ej
		MOVS	R0, #0xAA
		POP	{R4-R7,PC}
; End of function sub_1FFFF1E0


; =============== S U B	R O U T	I N E =======================================


sub_1FFFF22E				; CODE XREF: ROM:loc_1FFFF322p
					; ROM:loc_1FFFF35Ep ...
		PUSH	{R4-R6,LR}
		BL	jiancedubaohu_1FFFF124 ; ¼ì²â¶Á±£»¤
		CMP	R0, #0
		BNE	loc_1FFFF276
		MOVS	R0, #0x79
		BL	sub_1FFFF164
		BL	weigou_1FFFF19A
		MOV	R4, R0
		LSLS	R5, R0,	#0x18
		BL	weigou_1FFFF19A
		LSLS	R6, R0,	#0x10
		ORRS	R6, R5
		MOV	R5, R4
		EORS	R5, R0
		BL	weigou_1FFFF19A
		LSLS	R4, R0,	#8
		ORRS	R4, R6
		EORS	R5, R0
		BL	weigou_1FFFF19A
		ORRS	R4, R0
		EORS	R5, R0
		BL	weigou_1FFFF19A
		CMP	R0, R5
		BNE	loc_1FFFF276
		MOVS	R0, #0x79
		BL	sub_1FFFF164
		MOV	R0, R4
		POP	{R4-R6,PC}
; ---------------------------------------------------------------------------

loc_1FFFF276				; CODE XREF: sub_1FFFF22E+8j
					; sub_1FFFF22E+3Cj
		MOVS	R0, #0x1F
		BL	sub_1FFFF164
		LDR	R0, =0x55555555
		POP	{R4-R6,PC}
; End of function sub_1FFFF22E

; ---------------------------------------------------------------------------

loc_1FFFF280				; CODE XREF: ROM:1FFFEE1Aj
		SUB	SP, SP,	#0x1FC
		SUB	SP, SP,	#0x1FC
		SUB	SP, SP,	#0x10

loc_1FFFF286				; CODE XREF: ROM:loc_1FFFF2EAj
					; ROM:1FFFF320j ...
		LDR	R1, =0x40003000
		LDR	R0, =0xAAAA
		STR	R0, [R1]
		BL	weigou_1FFFF19A
		MOV	R4, R0
		BL	weigou_1FFFF19A
		MOV	R1, R0
		EORS	R1, R4
		CMP	R1, #0xFF
		BEQ	loc_1FFFF2A0
		MOVS	R4, #0x55

loc_1FFFF2A0				; CODE XREF: ROM:1FFFF29Cj
		CMP	R4, #0x31
		BEQ	loc_1FFFF38A
		BGT	loc_1FFFF2C0
		CMP	R4, #2
		BEQ	loc_1FFFF302
		BGT	loc_1FFFF2B6
		CMP	R4, #0
		BEQ	loc_1FFFF2DA
		CMP	R4, #1

loc_1FFFF2B2				; CODE XREF: ROM:1FFFF2BCj
					; ROM:1FFFF2CCj ...
		BNE	loc_1FFFF388
		B	loc_1FFFF2EC
; ---------------------------------------------------------------------------

loc_1FFFF2B6				; CODE XREF: ROM:1FFFF2AAj
		CMP	R4, #0x11
		BEQ	loc_1FFFF322
		CMP	R4, #0x21
		BNE	loc_1FFFF2B2
		B	loc_1FFFF35E
; ---------------------------------------------------------------------------

loc_1FFFF2C0				; CODE XREF: ROM:1FFFF2A4j
		CMP	R4, #0x73
		BEQ	loc_1FFFF3BE
		BGT	loc_1FFFF2D0
		CMP	R4, #0x44
		BEQ	loc_1FFFF3C0
		CMP	R4, #0x63
		BNE	loc_1FFFF2B2
		B	loc_1FFFF4D4
; ---------------------------------------------------------------------------

loc_1FFFF2D0				; CODE XREF: ROM:1FFFF2C4j
		CMP	R4, #0x82
		BEQ	loc_1FFFF3C2
		CMP	R4, #0x92
		BNE	loc_1FFFF2B2
		B	loc_1FFFF57E
; ---------------------------------------------------------------------------

loc_1FFFF2DA				; CODE XREF: ROM:1FFFF2AEj
		LDR	R2, =0x1FFFF756
		MOVS	R3, #0

loc_1FFFF2DE				; CODE XREF: ROM:1FFFF2E8j
		LDRB	R0, [R2,R3]
		BL	sub_1FFFF164
		ADDS	R3, R3,	#1
		CMP	R3, #0xF
		BCC	loc_1FFFF2DE

loc_1FFFF2EA				; CODE XREF: ROM:1FFFF3B0j
		B	loc_1FFFF286
; ---------------------------------------------------------------------------

loc_1FFFF2EC				; CODE XREF: ROM:1FFFF2B4j
		MOVS	R0, #0x79
		BL	sub_1FFFF164
		MOVS	R0, #0x31
		BL	sub_1FFFF164
		MOVS	R0, #0
		BL	sub_1FFFF164
		MOVS	R0, #0
		B	loc_1FFFF316
; ---------------------------------------------------------------------------

loc_1FFFF302				; CODE XREF: ROM:1FFFF2A8j
		MOVS	R0, #0x79
		BL	sub_1FFFF164
		MOVS	R0, #1
		BL	sub_1FFFF164
		MOVS	R0, #4
		BL	sub_1FFFF164
		MOVS	R0, #0x44

loc_1FFFF316				; CODE XREF: ROM:1FFFF300j
		BL	sub_1FFFF164
		B	loc_1FFFF4D0
; ---------------------------------------------------------------------------

loc_1FFFF31C				; CODE XREF: ROM:1FFFF4A2j
					; ROM:1FFFF4D2j
		BL	sub_1FFFF164
		B	loc_1FFFF286
; ---------------------------------------------------------------------------

loc_1FFFF322				; CODE XREF: ROM:1FFFF2B8j
		BL	sub_1FFFF22E
		MOV	R5, R0
		BL	sub_1FFFEF10
		UXTB	R0, R0
		CMP	R0, #1
		BEQ	loc_1FFFF388
		BL	weigou_1FFFF19A
		MOV	R4, R0
		MVNS	R0, R4
		UXTB	R6, R0
		BL	weigou_1FFFF19A
		CMP	R0, R6
		BNE	loc_1FFFF388
		MOVS	R0, #0x79
		BL	sub_1FFFF164
		ADDS	R4, R4,	#1
		BEQ	loc_1FFFF286

loc_1FFFF34E				; CODE XREF: ROM:1FFFF35Aj
		MOV	R0, R5
		ADDS	R5, R5,	#1
		LDRB	R0, [R0]
		BL	sub_1FFFF164
		SUBS	R4, R4,	#1
		BNE	loc_1FFFF34E
		B	loc_1FFFF286
; ---------------------------------------------------------------------------

loc_1FFFF35E				; CODE XREF: ROM:1FFFF2BEj
		BL	sub_1FFFF22E
		MOV	R4, R0
		BL	sub_1FFFEF10
		UXTB	R0, R0
		CMP	R0, #2
		BEQ	loc_1FFFF372
		CMP	R0, #3
		BNE	loc_1FFFF388

loc_1FFFF372				; CODE XREF: ROM:1FFFF36Cj
		BL	qingchuRCC_1FFFEEA8
		BL	kaizhongduan_1FFFECC2
		LDR	R5, [R4,#4]
		LDR	R0, [R4]
		BL	byte_1FFFECB8
		BLX	R5
		B	loc_1FFFF286
; ---------------------------------------------------------------------------
		DCB    0
		DCB 0xE0 ; à
; ---------------------------------------------------------------------------

loc_1FFFF388				; CODE XREF: ROM:loc_1FFFF2B2j
					; ROM:1FFFF330j ...
		B	loc_1FFFF498
; ---------------------------------------------------------------------------

loc_1FFFF38A				; CODE XREF: ROM:1FFFF2A2j
		BL	sub_1FFFF22E
		MOV	R7, R0
		BL	sub_1FFFEF10
		UXTB	R0, R0
		STR	R0, [SP]
		CMP	R0, #1
		BEQ	loc_1FFFF498
		CMP	R0, #5
		BEQ	loc_1FFFF4A0
		BL	weigou_1FFFF19A
		ADD	R1, SP,	#4
		ADDS	R4, R0,	#1
		MOV	R6, R1
		BL	sub_1FFFF1B2
		CMP	R0, #0xAA
		BNE	loc_1FFFF2EA
		LDR	R0, [SP]
		CMP	R0, #2
		BEQ	loc_1FFFF3C4
		CMP	R0, #3
		BEQ	loc_1FFFF3EE
		B	loc_1FFFF3E6
; ---------------------------------------------------------------------------

loc_1FFFF3BE				; CODE XREF: ROM:1FFFF2C2j
		B	loc_1FFFF51A
; ---------------------------------------------------------------------------

loc_1FFFF3C0				; CODE XREF: ROM:1FFFF2C8j
		B	loc_1FFFF464
; ---------------------------------------------------------------------------

loc_1FFFF3C2				; CODE XREF: ROM:1FFFF2D2j
		B	loc_1FFFF534
; ---------------------------------------------------------------------------

loc_1FFFF3C4				; CODE XREF: ROM:1FFFF3B6j
		LSLS	R0, R4,	#0x1E
		BEQ	loc_1FFFF3CE
		MOVS	R0, #0xFC
		ANDS	R4, R0
		ADDS	R4, R4,	#4

loc_1FFFF3CE				; CODE XREF: ROM:1FFFF3C6j
		BL	FPECjiesuo_1FFFEF62 ; FPEC½âËø
		MOVS	R5, R4
		BEQ	loc_1FFFF3E6

loc_1FFFF3D6				; CODE XREF: ROM:1FFFF3E4j
		SUBS	R0, R6,	R5
		LDR	R1, [R0,R4]
		SUBS	R0, R7,	R5
		ADDS	R0, R0,	R4
		BL	xieflash_1FFFEF9A ; ±à³Ì
		SUBS	R5, R5,	#4
		BNE	loc_1FFFF3D6

loc_1FFFF3E6				; CODE XREF: ROM:1FFFF3BCj
					; ROM:1FFFF3D4j
		LDR	R0, [SP]
		CMP	R0, #4
		BEQ	loc_1FFFF40A
		B	loc_1FFFF4D0
; ---------------------------------------------------------------------------

loc_1FFFF3EE				; CODE XREF: ROM:1FFFF3BAj
		LSLS	R0, R4,	#0x1E
		BEQ	loc_1FFFF3F8
		MOVS	R0, #0xFC
		ANDS	R4, R0
		ADDS	R4, R4,	#4

loc_1FFFF3F8				; CODE XREF: ROM:1FFFF3F0j
		MOVS	R0, R4
		BEQ	loc_1FFFF4D0

loc_1FFFF3FC				; CODE XREF: ROM:1FFFF406j
		SUBS	R1, R6,	R0
		LDR	R1, [R1,R4]
		SUBS	R2, R7,	R0
		STR	R1, [R2,R4]
		SUBS	R0, R0,	#4
		BNE	loc_1FFFF3FC
		B	loc_1FFFF4D0
; ---------------------------------------------------------------------------

loc_1FFFF40A				; CODE XREF: ROM:1FFFF3EAj
		LDR	R0, =word_1FFFF800
		CMP	R7, R0
		BNE	loc_1FFFF4D0
		LSLS	R0, R4,	#0x1F
		BEQ	loc_1FFFF41A
		MOVS	R0, #0xFE
		ANDS	R4, R0
		ADDS	R4, R4,	#2

loc_1FFFF41A				; CODE XREF: ROM:1FFFF412j
		BL	xuanzezijiecachu_1FFFF020 ; Ñ¡Ïî×Ö½Ú²Á³ý
		BL	FPECjiesuo_1FFFEF62 ; FPEC½âËø
		BL	OPTWREjiesuo_1FFFEF6E ;	OPTWRE½âËø
		LDR	R0, =0x40022000
		LDR	R1, [R0,#0x10]
		MOVS	R2, #0x10
		ORRS	R1, R2
		STR	R1, [R0,#0x10]
		BL	flashmang_1FFFEF7A ; flash Ã¦
		MOVS	R5, R4
		BEQ	loc_1FFFF44A

loc_1FFFF438				; CODE XREF: ROM:1FFFF448j
		SUBS	R0, R6,	R5
		LDRH	R0, [R0,R4]
		SUBS	R1, R7,	R5
		UXTB	R0, R0
		STRH	R0, [R1,R4]
		BL	flashmang_1FFFEF7A ; flash Ã¦
		SUBS	R5, R5,	#2
		BNE	loc_1FFFF438

loc_1FFFF44A				; CODE XREF: ROM:1FFFF436j
		LDR	R0, =0x40022000
		LDR	R1, [R0,#0x10]
		MOVS	R2, #0x10
		BICS	R1, R2
		STR	R1, [R0,#0x10]
		MOVS	R0, #0x79
		BL	sub_1FFFF164
		BL	xuanzezijieqiangzhigengxin_1FFFF132 ; Ñ¡Ïî×Ö½ÚÇ¿ÖÆ¸üÐÂ
		BL	fuwei_1FFFECD8
		B	loc_1FFFF4D0
; ---------------------------------------------------------------------------

loc_1FFFF464				; CODE XREF: ROM:loc_1FFFF3C0j
		BL	jiancedubaohu_1FFFF124 ; ¼ì²â¶Á±£»¤
		CMP	R0, #1
		BEQ	loc_1FFFF4A0
		MOVS	R0, #0x79
		BL	sub_1FFFF164
		BL	weigou_1FFFF19A
		MOV	R4, R0
		BL	weigou_1FFFF19A
		LSLS	R1, R4,	#8
		ORRS	R0, R1
		LDR	R2, =0xFFF
		LSRS	R1, R0,	#4
		CMP	R1, R2
		BNE	loc_1FFFF4AA
		LDR	R1, =0xFFFF
		CMP	R0, R1
		BNE	loc_1FFFF4A4
		BL	weigou_1FFFF19A
		CMP	R0, #0
		BNE	loc_1FFFF4A0
		B	loc_1FFFF49A
; ---------------------------------------------------------------------------

loc_1FFFF498				; CODE XREF: ROM:loc_1FFFF388j
					; ROM:1FFFF39Aj
		B	loc_1FFFF4A0
; ---------------------------------------------------------------------------

loc_1FFFF49A				; CODE XREF: ROM:1FFFF496j
		BL	zhengpian_1FFFEFF8 ; ÕûÆ¬²Á³ý
		B	loc_1FFFF4D0
; ---------------------------------------------------------------------------

loc_1FFFF4A0				; CODE XREF: ROM:1FFFF39Ej
					; ROM:1FFFF46Aj ...
		MOVS	R0, #0x1F
		B	loc_1FFFF31C
; ---------------------------------------------------------------------------

loc_1FFFF4A4				; CODE XREF: ROM:1FFFF48Cj
		BL	weigou_1FFFF19A
		B	loc_1FFFF4A0
; ---------------------------------------------------------------------------

loc_1FFFF4AA				; CODE XREF: ROM:1FFFF486j
		ADD	R1, SP,	#4
		ADDS	R4, R0,	#1
		MOV	R5, R1
		BL	sub_1FFFF1E0
		CMP	R0, #0xAA
		BNE	loc_1FFFF4A0
		CMP	R4, #0
		BEQ	loc_1FFFF4D0
		MOVS	R6, #0x8000000

loc_1FFFF4C0				; CODE XREF: ROM:1FFFF4CEj
		LDRH	R0, [R5]
		LSLS	R0, R0,	#0xA
		ADDS	R0, R0,	R6
		BL	yecachu_1FFFEFDA ; Ò³²Á³ý
		ADDS	R5, R5,	#2
		SUBS	R4, R4,	#1
		BNE	loc_1FFFF4C0

loc_1FFFF4D0				; CODE XREF: ROM:1FFFF31Aj
					; ROM:1FFFF3ECj ...
		MOVS	R0, #0x79
		B	loc_1FFFF31C
; ---------------------------------------------------------------------------

loc_1FFFF4D4				; CODE XREF: ROM:1FFFF2CEj
		BL	jiancedubaohu_1FFFF124 ; ¼ì²â¶Á±£»¤
		CMP	R0, #1
		BEQ	loc_1FFFF4A0
		MOVS	R0, #0x79
		BL	sub_1FFFF164
		BL	weigou_1FFFF19A
		ADD	R1, SP,	#4
		ADDS	R4, R0,	#1
		MOV	R5, R1
		BL	sub_1FFFF1B2
		CMP	R0, #0xAA
		BEQ	loc_1FFFF4F6
		B	loc_1FFFF286
; ---------------------------------------------------------------------------

loc_1FFFF4F6				; CODE XREF: ROM:1FFFF4F2j
		MOVS	R6, #0
		CMP	R4, #0
		BEQ	loc_1FFFF50E
		MOVS	R0, #1

loc_1FFFF4FE				; CODE XREF: ROM:1FFFF50Cj
		MOV	R1, R5
		LDRB	R2, [R1]
		ADDS	R5, R5,	#1
		MOV	R1, R0
		LSLS	R1, R2
		ORRS	R6, R1
		SUBS	R4, R4,	#1
		BNE	loc_1FFFF4FE

loc_1FFFF50E				; CODE XREF: ROM:1FFFF4FAj
		BL	FPECjiesuo_1FFFEF62 ; FPEC½âËø
		MOV	R0, R6
		BL	zijiebiancheng_1FFFF048	; ×Ö½Ú±à³Ì
		B	loc_1FFFF52C
; ---------------------------------------------------------------------------

loc_1FFFF51A				; CODE XREF: ROM:loc_1FFFF3BEj
		BL	jiancedubaohu_1FFFF124 ; ¼ì²â¶Á±£»¤
		CMP	R0, #1
		BEQ	loc_1FFFF4A0
		MOVS	R0, #0x79
		BL	sub_1FFFF164
		MOVS	R0, #0
		B	loc_1FFFF544
; ---------------------------------------------------------------------------

loc_1FFFF52C				; CODE XREF: ROM:1FFFF518j
					; ROM:1FFFF548j
		MOVS	R0, #0x79
		BL	sub_1FFFF164
		B	loc_1FFFF578
; ---------------------------------------------------------------------------

loc_1FFFF534				; CODE XREF: ROM:loc_1FFFF3C2j
		BL	jiancedubaohu_1FFFF124 ; ¼ì²â¶Á±£»¤
		CMP	R0, #1
		BEQ	loc_1FFFF4A0
		MOVS	R0, #0x79
		BL	sub_1FFFF164
		MOVS	R0, #1

loc_1FFFF544				; CODE XREF: ROM:1FFFF52Aj
		BL	xiebaohu_1FFFF0A6 ; Ð´±£»¤
		B	loc_1FFFF52C
; ---------------------------------------------------------------------------
		DCB    0
		DCB    0
dword_1FFFF54C	DCD 0x20000000		; DATA XREF: sub_1FFFF164r
					; sub_1FFFF172+10r ...
dword_1FFFF550	DCD 0x20000004		; DATA XREF: sub_1FFFF172+6r
dword_1FFFF554	DCD 0x140D		; DATA XREF: sub_1FFFF172+16r
dword_1FFFF558	DCD 0xAAAA		; DATA XREF: weigou_1FFFF19A+2r
					; ROM:1FFFF288r
dword_1FFFF55C	DCD 0x40003000		; DATA XREF: weigou_1FFFF19A+6r
					; ROM:loc_1FFFF286r
dword_1FFFF560	DCD 0x55555555		; DATA XREF: sub_1FFFF22E+4Er
dword_1FFFF564	DCD 0x1FFFF756		; DATA XREF: ROM:loc_1FFFF2DAr
off_1FFFF568	DCD word_1FFFF800	; DATA XREF: ROM:loc_1FFFF40Ar
dword_1FFFF56C	DCD 0x40022000		; DATA XREF: ROM:1FFFF426r
					; ROM:loc_1FFFF44Ar
dword_1FFFF570	DCD 0xFFF		; DATA XREF: ROM:1FFFF480r
dword_1FFFF574	DCD 0xFFFF		; DATA XREF: ROM:1FFFF488r
; ---------------------------------------------------------------------------

loc_1FFFF578				; CODE XREF: ROM:1FFFF532j
					; ROM:1FFFF594j
		BL	xuanzezijieqiangzhigengxin_1FFFF132 ; Ñ¡Ïî×Ö½ÚÇ¿ÖÆ¸üÐÂ
		B	loc_1FFFF286
; ---------------------------------------------------------------------------

loc_1FFFF57E				; CODE XREF: ROM:1FFFF2D8j
		MOVS	R0, #0x79
		BL	sub_1FFFF164
		MOVS	R0, #0
		BL	xiebaohu_1FFFF0A6 ; Ð´±£»¤
		MOVS	R0, #0x79
		BL	sub_1FFFF164
		BL	sub_1FFFEF50
		B	loc_1FFFF578

; =============== S U B	R O U T	I N E =======================================


sub_1FFFF596				; CODE XREF: sub_1FFFF172+Cp
		MOVS	R2, #0
		LSRS	R3, R0,	#4
		CMP	R3, R1
		BCC	loc_1FFFF5F8
		LSRS	R3, R0,	#8
		CMP	R3, R1
		BCC	loc_1FFFF5C8
		MOVS	R3, #0
		MOV	R12, R3
		B	loc_1FFFF648
; ---------------------------------------------------------------------------
		MOV	R3, R0
		ORRS	R3, R1
		BMI	loc_1FFFF62A
		MOVS	R2, #0
		LSRS	R3, R0,	#1
		CMP	R3, R1
		BCC	loc_1FFFF61C
		LSRS	R3, R0,	#4
		CMP	R3, R1
		BCC	loc_1FFFF5F8
		LSRS	R3, R0,	#8
		CMP	R3, R1
		BCC	loc_1FFFF5C8
		MOV	R12, R2
		B	loc_1FFFF648
; ---------------------------------------------------------------------------

loc_1FFFF5C8				; CODE XREF: sub_1FFFF596+Cj
					; sub_1FFFF596+2Cj
		LSRS	R3, R0,	#7
		CMP	R3, R1
		BCC	loc_1FFFF5D2
		LSLS	R3, R1,	#7
		SUBS	R0, R0,	R3

loc_1FFFF5D2				; CODE XREF: sub_1FFFF596+36j
		ADCS	R2, R2
		LSRS	R3, R0,	#6
		CMP	R3, R1
		BCC	loc_1FFFF5DE
		LSLS	R3, R1,	#6
		SUBS	R0, R0,	R3

loc_1FFFF5DE				; CODE XREF: sub_1FFFF596+42j
		ADCS	R2, R2
		LSRS	R3, R0,	#5
		CMP	R3, R1
		BCC	loc_1FFFF5EA
		LSLS	R3, R1,	#5
		SUBS	R0, R0,	R3

loc_1FFFF5EA				; CODE XREF: sub_1FFFF596+4Ej
		ADCS	R2, R2
		LSRS	R3, R0,	#4
		CMP	R3, R1
		BCC	loc_1FFFF5F6
		LSLS	R3, R1,	#4
		SUBS	R0, R0,	R3

loc_1FFFF5F6				; CODE XREF: sub_1FFFF596+5Aj
		ADCS	R2, R2

loc_1FFFF5F8				; CODE XREF: sub_1FFFF596+6j
					; sub_1FFFF596+26j
		LSRS	R3, R0,	#3
		CMP	R3, R1
		BCC	loc_1FFFF602
		LSLS	R3, R1,	#3
		SUBS	R0, R0,	R3

loc_1FFFF602				; CODE XREF: sub_1FFFF596+66j
		ADCS	R2, R2
		LSRS	R3, R0,	#2
		CMP	R3, R1
		BCC	loc_1FFFF60E
		LSLS	R3, R1,	#2
		SUBS	R0, R0,	R3

loc_1FFFF60E				; CODE XREF: sub_1FFFF596+72j
		ADCS	R2, R2
		LSRS	R3, R0,	#1
		CMP	R3, R1
		BCC	loc_1FFFF61A
		LSLS	R3, R1,	#1
		SUBS	R0, R0,	R3

loc_1FFFF61A				; CODE XREF: sub_1FFFF596+7Ej
		ADCS	R2, R2

loc_1FFFF61C				; CODE XREF: sub_1FFFF596+20j
		SUBS	R1, R0,	R1
		BCS	loc_1FFFF622
		MOV	R1, R0

loc_1FFFF622				; CODE XREF: sub_1FFFF596+88j
		ADCS	R2, R2
		MOV	R0, R2
		BX	LR
; ---------------------------------------------------------------------------
		B	loc_1FFFF6E6
; ---------------------------------------------------------------------------

loc_1FFFF62A				; CODE XREF: sub_1FFFF596+18j
		LSRS	R2, R1,	#0x1F
		BEQ	loc_1FFFF630
		NEGS	R1, R1

loc_1FFFF630				; CODE XREF: sub_1FFFF596+96j
		ASRS	R3, R0,	#0x20
		BCC	loc_1FFFF636
		NEGS	R0, R0

loc_1FFFF636				; CODE XREF: sub_1FFFF596+9Cj
		EORS	R3, R2
		MOVS	R2, #0
		MOV	R12, R3
		LSRS	R3, R0,	#4
		CMP	R3, R1
		BCC	loc_1FFFF69E
		LSRS	R3, R0,	#8
		CMP	R3, R1
		BCC	loc_1FFFF66E

loc_1FFFF648				; CODE XREF: sub_1FFFF596+12j
					; sub_1FFFF596+30j
		MOVS	R2, #0xFC
		LSLS	R1, R1,	#6
		REV	R2, R2
		LSRS	R3, R0,	#8
		CMP	R3, R1
		BCC	loc_1FFFF66E
		LSLS	R1, R1,	#6
		ASRS	R2, R2,	#6
		CMP	R3, R1
		BCC	loc_1FFFF66E
		LSLS	R1, R1,	#6
		ASRS	R2, R2,	#6
		CMP	R3, R1
		BCC	loc_1FFFF66E
		LSLS	R1, R1,	#6
		BEQ	loc_1FFFF6DE
		ASRS	R2, R2,	#6
		B	loc_1FFFF66E
; ---------------------------------------------------------------------------

loc_1FFFF66C				; CODE XREF: sub_1FFFF596+120j
		LSRS	R1, R1,	#6

loc_1FFFF66E				; CODE XREF: sub_1FFFF596+B0j
					; sub_1FFFF596+BCj ...
		LSRS	R3, R0,	#7
		CMP	R3, R1
		BCC	loc_1FFFF678
		LSLS	R3, R1,	#7
		SUBS	R0, R0,	R3

loc_1FFFF678				; CODE XREF: sub_1FFFF596+DCj
		ADCS	R2, R2
		LSRS	R3, R0,	#6
		CMP	R3, R1
		BCC	loc_1FFFF684
		LSLS	R3, R1,	#6
		SUBS	R0, R0,	R3

loc_1FFFF684				; CODE XREF: sub_1FFFF596+E8j
		ADCS	R2, R2
		LSRS	R3, R0,	#5
		CMP	R3, R1
		BCC	loc_1FFFF690
		LSLS	R3, R1,	#5
		SUBS	R0, R0,	R3

loc_1FFFF690				; CODE XREF: sub_1FFFF596+F4j
		ADCS	R2, R2
		LSRS	R3, R0,	#4
		CMP	R3, R1
		BCC	loc_1FFFF69C
		LSLS	R3, R1,	#4
		SUBS	R0, R0,	R3

loc_1FFFF69C				; CODE XREF: sub_1FFFF596+100j
		ADCS	R2, R2

loc_1FFFF69E				; CODE XREF: sub_1FFFF596+AAj
		LSRS	R3, R0,	#3
		CMP	R3, R1
		BCC	loc_1FFFF6A8
		LSLS	R3, R1,	#3
		SUBS	R0, R0,	R3

loc_1FFFF6A8				; CODE XREF: sub_1FFFF596+10Cj
		ADCS	R2, R2
		LSRS	R3, R0,	#2
		CMP	R3, R1
		BCC	loc_1FFFF6B4
		LSLS	R3, R1,	#2
		SUBS	R0, R0,	R3

loc_1FFFF6B4				; CODE XREF: sub_1FFFF596+118j
		ADCS	R2, R2
		BCS	loc_1FFFF66C
		LSRS	R3, R0,	#1
		CMP	R3, R1
		BCC	loc_1FFFF6C2
		LSLS	R3, R1,	#1
		SUBS	R0, R0,	R3

loc_1FFFF6C2				; CODE XREF: sub_1FFFF596+126j
		ADCS	R2, R2
		SUBS	R1, R0,	R1
		BCS	loc_1FFFF6CA
		MOV	R1, R0

loc_1FFFF6CA				; CODE XREF: sub_1FFFF596+130j
		MOV	R3, R12
		ADCS	R2, R2
		ASRS	R3, R3,	#1
		MOV	R0, R2
		BCC	loc_1FFFF6D8
		NEGS	R0, R0
		CMP	R3, #0

loc_1FFFF6D8				; CODE XREF: sub_1FFFF596+13Cj
		BPL	locret_1FFFF6DC
		NEGS	R1, R1

locret_1FFFF6DC				; CODE XREF: sub_1FFFF596:loc_1FFFF6D8j
		BX	LR
; ---------------------------------------------------------------------------

loc_1FFFF6DE				; CODE XREF: sub_1FFFF596+D0j
		MOV	R3, R12
		ASRS	R3, R3,	#1
		BCC	loc_1FFFF6E6
		NEGS	R0, R0

loc_1FFFF6E6				; CODE XREF: sub_1FFFF596+92j
					; sub_1FFFF596+14Cj
		PUSH	{R0,LR}
		MOVS	R0, #0
		NOP
		NOP
		POP	{R1,PC}
; End of function sub_1FFFF596

; ---------------------------------------------------------------------------
		DCB 0x70 ; p
		DCB 0x47 ; G
		DCB 0x70 ; p
		DCB 0x47 ; G
		DCB 0x70 ; p
		DCB 0x47 ; G

; =============== S U B	R O U T	I N E =======================================


sub_1FFFF6F6				; CODE XREF: ROM:loc_1FFFEC98p
		MOV	R5, LR
		BL	sub_1FFFF740
		MOV	LR, R5
		MOVS	R5, R0
		MOV	R1, SP
		MOV	R3, R10
		LSRS	R0, R0,	#3
		LSLS	R0, R0,	#3
		MOV	SP, R0
		ADD	SP, SP,	#0x60
		PUSH	{R5,LR}
		BL	sub_1FFFEE64
		POP	{R5,R6}
		MOVS	R7, #0
		LSRS	R1, R1,	#1
		MOV	LR, R6
		MOVS	R6, #0
		STMIA	R5!, {R6,R7}
		STMIA	R5!, {R6,R7}
		STMIA	R5!, {R6,R7}
		STMIA	R5!, {R6,R7}
		STMIA	R5!, {R6,R7}
		STMIA	R5!, {R6,R7}
		STMIA	R5!, {R6,R7}
		STMIA	R5!, {R6,R7}
		SUBS	R5, #0x40
		LSLS	R1, R1,	#1
		MOV	SP, R1
		BX	LR
; End of function sub_1FFFF6F6

; ---------------------------------------------------------------------------

loc_1FFFF734				; CODE XREF: ROM:1FFFECA6j
		MOV	R4, R0
		NOP
		NOP
		MOV	R0, R4
		BL	meiyong_1FFFECAA

; =============== S U B	R O U T	I N E =======================================


sub_1FFFF740				; CODE XREF: sub_1FFFF6F6+2p
		LDR	R0, =0x20000010
		BX	LR
; End of function sub_1FFFF740

; ---------------------------------------------------------------------------
dword_1FFFF744	DCD 0x20000010		; DATA XREF: sub_1FFFF740r

; =============== S U B	R O U T	I N E =======================================

; Attributes: noreturn

BKPTduandian_1FFFF748			; CODE XREF: meiyong_1FFFECAA+8p
		LDR	R1, =0x20026
		MOVS	R0, #0x18
		BKPT	0xAB

loc_1FFFF74E				; CODE XREF: BKPTduandian_1FFFF748:loc_1FFFF74Ej
		B	loc_1FFFF74E
; End of function BKPTduandian_1FFFF748

; ---------------------------------------------------------------------------
dword_1FFFF750	DCD 0x20026		; DATA XREF: BKPTduandian_1FFFF748r
		DCB 0x70 ; p
		DCB 0x47 ; G
		DCB 0x79 ; y
		DCB  0xB
		DCB 0x31 ; 1
		DCB    0
		DCB    1
		DCB    2
		DCB 0x11
		DCB 0x21 ; !
		DCB 0x31 ; 1
		DCB 0x44 ; D
		DCB 0x63 ; c
		DCB 0x73 ; s
		DCB 0x82 ; ‚
		DCB 0x92 ; ’
		DCB 0x79 ; y
		DCB    0
		DCB    0
		DCB    0
		DCB 0x88 ; ˆ
		DCB 0xF7 ; ÷
		DCB 0xFF
		DCB 0x1F
		DCB    0
		DCB    0
		DCB    0
		DCB 0x20
		DCB 0x10
		DCB    0
		DCB    0
		DCB    0
		DCB 0x54 ; T
		DCB 0xEC ; ì
		DCB 0xFF
		DCB 0x1F
		DCB 0x98 ; ˜
		DCB 0xF7 ; ÷
		DCB 0xFF
		DCB 0x1F
		DCB 0x10
		DCB    0
		DCB    0
		DCB 0x20
		DCB 0x60 ; `
		DCB    6
		DCB    0
		DCB    0
		DCB 0x70 ; p
		DCB 0xEC ; ì
		DCB 0xFF
		DCB 0x1F
		DCB    0
		DCB 0x38 ; 8
		DCB    1
		DCB 0x40 ; @
		DCB    0
		DCB    0
		DCB    0
		DCB    0
		DCB    0
		DCB    0
		DCB    0
		DCB    0
		DCB    0
		DCB    0
		DCB    0
		DCB    0
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0x31 ; 1
		DCB    0
		DCB 0x10
		DCB    0
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0x1E
		DCB    0
		DCB 0x2A ; *
		DCB    0
		DCB 0x17
		DCB 0x57 ; W
		DCB 0x33 ; 3
		DCB 0x53 ; S
		DCB 0x39 ; 9
		DCB 0x34 ; 4
		DCB 0x37 ; 7
		DCB 0x20
		DCB 0xE7 ; ç
		DCB    6
		DCB 0xF2 ; ò
		DCB    5
		DCB 0xF0 ; ð
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0x3D ; =
		DCB    5
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFC ; ü
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0x10
		DCB    0
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xF3 ; ó
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0x68 ; h
		DCB 0x97 ; —
		DCB 0x5B ; [
		DCB 0xA4 ; ¤
		DCB 0x42 ; B
		DCB 0xBD ; ½
		DCB 0x3F ; ?
		DCB 0xC0 ; À
word_1FFFF800	DCW 0x55AA		; DATA XREF: zijiebiancheng_1FFFF048+6r
					; zijiebiancheng_1FFFF048+2Cw ...
word_1FFFF802	DCW 0xFFFF		; DATA XREF: zijiebiancheng_1FFFF048+8r
					; zijiebiancheng_1FFFF048+36w ...
word_1FFFF804	DCW 0xFFFF		; DATA XREF: xiebaohu_1FFFF0A6+Er
					; xiebaohu_1FFFF0A6+44w
word_1FFFF806	DCW 0xFFFF		; DATA XREF: xiebaohu_1FFFF0A6+10r
					; xiebaohu_1FFFF0A6+4Cw
word_1FFFF808	DCW 0xFFFF		; DATA XREF: zijiebiancheng_1FFFF048+40w
					; xiebaohu_1FFFF0A6+12r ...
word_1FFFF80A	DCW 0xFFFF		; DATA XREF: zijiebiancheng_1FFFF048+4Aw
					; xiebaohu_1FFFF0A6+16r
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
		DCB 0xFF
; ROM		ends

		END
