#!/usr/bin/env bash

# $0 func
# lists *.cc files that call func()

#if [ ! -f scripts/cc.lst ]; then
#    echo 'run  "make tags" !';
#    exit 1;
#fi
#CCFILES=$(cat scripts/cc.lst)
CCFILES='*/*.cc'

grep -E -l "^.+\b$1\(" $CCFILES


#HFILES=$(cat scripts/hh.lst)
#grep  -E -l "^.+\b$1\b" $HFILES


exit 0;
########################
